### ISSUE TITLE
JsonSerializable: generate valid lists in strong mode 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/source_gen#104]
Currently, lists will generate a constructor like this:

```dart
// source
class User extends Object with _$UserSerializerMixin {
  List<int> tags;
  User(this.tags);
  factory User.fromJson(Map json) => _$UserFromJson(json);
}

// generated
User _$UserFromJson(Map json) => new User(
(json['tags'] as List)?.map((v0) => v0)?.toList());
```

Which generates the following strong-mode error:

```
WARNING: Unsafe implicit cast from 'List<dynamic>' to 'List<int>'. This usually indicates that type information was lost and resulted in 'dynamic' and/or a place that will have a failure at runtime. ([revolution] lib/model.g.dart:725)
```

**Comment by kevmoo** [comment]
Good catch! Pull requests welcome!

**Comment by kevmoo** [comment]
This is the spot - https://github.com/dart-lang/source_gen/blob/ff9de155694effff4afbfa972b75e748e03b6e9f/lib/generators/json_serializable_generator.dart#L235

Just need to find a clean way to determine that the incoming value is what we want to store – and to reflect the target type.

**Comment by johnpryan** [comment]
awesome - thanks @a14n !
