### ISSUE TITLE
SourceGen should handle part files properly

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/source_gen#114]
Right now, if foo.dart is part of bar.dart, we still attempt to generate foo.g.dart. We should only generate bar.g.dart, and include any generated code from foo.dart in there.

**Comment by natebosch** [comment]
We both went to file at the same time :)

Will close this one and track in https://github.com/dart-lang/source_gen/issues/114

**Comment by natebosch** [comment]
Ugh, track in https://github.com/dart-lang/source_gen/issues/115
