### ISSUE TITLE
Make StandaloneBuilder a separate class from GeneratorBuilder

### ISSUE THREAD

**Issue by natebosch** [dart-lang/source_gen#117]
The api is confusing as is since it only allows a single Generator in standalone mode. We should make that explicit through the signature.

Once the constructor for GeneratorBuilder doesn't have a throw we can also make it `const` which is a common pattern for builders.

**Comment by natebosch** [comment]
Since we've got a good collection of use cases established I'm going to look at a deeper rewrite of the top level interfaces and how they can be put together. As part of that I'll rename `GeneratorBuilder` to `PartBuilder` and the new standalone concept will be called `SourceBuilder`.

Similarly `Generator` and `GeneratorForAnnotation` will be replace with some typedefs and I'll introduce `SourceGenerator` as the more general concept. We'll be able to put these concepts together to cover the 4 use cases we've seen.

- Build a `part of` file out of snippets for annotated code
- Build a `part of` file out of snippets for arbitrary `Element`s
- Build a standalone Dart source file for a library
- Build a standalone Dart source file + extra outputs for a library (with utilities to find annotated elements)

**Comment by matanlurey** [comment]
@natebosch Want some help doing this, since I'm driving (some of the) requirements?

When you're back from leave ping me :)

**Comment by natebosch** [comment]
I'll see if I can dig up the changes I started in this direction. I ended up hitting some places where I wanted to use functions but was forced to use classes because function generic arguments are erased at runtime - the UX wasn't what I hoped.

Adding this to my TODO list for when I return and I'll sync with you on either getting some help or putting out my prototype.

**Comment by natebosch** [comment]
Should be pretty straightforward at this point. The decision we need to make is what public surface area we want: `PartBuilder` and `LibraryBuilder`, or `GeneratorBuilder` and `GeneratorBuilder.standalone`...

@kevmoo @matanlurey any opinion?

I think the Part / Library distinction is easier to understand, but GeneratorBuilder.standalone would be a smaller change since clients who aren't passing `isStandalone` today wouldn't need to change anything.

**Comment by kevmoo** [comment]
Vote for LibraryBuilder + PartBuilder

CC @jakemac53
