### ISSUE TITLE
Make an executable

### ISSUE THREAD

**Issue by Rodsevich** [dart-lang/source_gen#124]
As stated [here](https://www.dartlang.org/tools/pub/cmd/pub-run), one can run executables from dependencies that are located in bin directory.

It would be fabulous this package provides that executable that could be configured _ad hoc_ via params:

`pub run source_gen:generate file --generators-config-file=generators.yaml `

_generators.yaml_ should contain the user-made generators that the executable could use for working, and a file like _source_gen.yaml_ could be the default location for that config file, as with _dart_test.yaml_ in the test package

By doing so, and with little or no extra modifications (now you have to make and configure files at tool directory), another generators packages that extends this one could be easily used as well:

`pub run zengen:watch directory`

**Comment by kevmoo** [comment]
I believe @natebosch is looking into this.

**Comment by natebosch** [comment]
This isn't a use case I'm working on, but a lot of the work going towards bazel should end up making this easier to tackle later on.
Seems like a good feature, will take a look once we've got the bazel approach figured out.

**Comment by matanlurey** [comment]
Is this still valid?

**Comment by natebosch** [comment]
this is still a use pattern I'd like to enable - I think though maybe the work will be done in package:build_runner rather than here. Running a Generator is a special case of running a Builder so if we make it easy to run any Builder we've solve this case as well.
