### ISSUE TITLE
Output failing file or build step on dart format failure

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#130]
> ```
> [SEVERE]: Error formatting the generated source code.
> This may indicate an issue in the generated code or in the formatter.
> Please check the generated code and file an issue on source_gen
> if approppriate.
> Could not format because the source could not be parsed:
> 
> line 1, column 6: Part-of directives must include a library name.
> part of ;
> ```

I don't have any information on what the failure is related to.

**Comment by kevmoo** [comment]
Help us with the code that was run?

**Comment by matanlurey** [comment]
FWIW, I figured it out - I was running a `Generator` that was outputting a `.json` file, but I forgot to say it was `isStandlone: true` - adding this line fixed it. I think if you don't have this set it assumes it is a Dart file and tries running the formatter, failing.
