### ISSUE TITLE
Consider helpers for static type reflection

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#136]
Within Angular today I'm working on a class called `StaticTypes`:

```dart
/// An abstraction around comparing types statically (at compile-time).
abstract class StaticTypes {
  /// Creates a [MetadataTypes] that uses runtime reflection.
  const factory StaticTypes.withMirrors({
    bool checkSubTypes,
  }) = _MirrorsStaticTypes;

  /// Creates a [MetadataTypes] by retrieving exact types from [resolver].
  ///
  /// With _analysis summaries_ this should be a relatively cheap operation but
  /// the resulting [MetadataTypes] class should still be cached whenever
  /// possible.
  ///
  /// Throws an [ArgumentError] if [resolver] was not able to lookup type
  /// information for Angular's metadata classes - this is usually a sign that
  /// dependencies or imports are missing.
  factory StaticTypes.fromResolver(
    Resolver resolver, {
    bool checkSubTypes,
  }) = ...
}
```

This could be useful to all users that are writing source-code generation/macros.

Would be happy to port/commonify this once complete. It could replace the hackier 'matchAnnotation' that is used within the `src/` folder today.

**Comment by matanlurey** [comment]
Ping @kevmoo @natebosch @jakemac53 - is this desirable?

**Comment by jakemac53** [comment]
Could you give a bit more information about this class, for instance what
instance methods do your forsee? Is it used to check if  an analyzer
`DartObject` is of a certain real `Type`?

**Comment by matanlurey** [comment]
Yep! Incidentally I'm in SEA today so I can show it off
