### ISSUE TITLE
Do we need source_gen/builder.dart? 

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#152]
It seems confusing since it's also exported through `source_gen.dart`.

Can we deprecate/remove?

**Comment by kevmoo** [comment]
CC @jakemac53 @natebosch

**Comment by jakemac53** [comment]
We probably don't need it - no (obviously a breaking change to remove it though so I would just deprecate it until the next breaking release?). I don't think its work a breaking release on its own.
