### ISSUE TITLE
Support non-library part files

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#157]
i.e. the format of `part of package:foo/foo.dart`.

**Comment by lrhn** [comment]
Can you elaborate on what you want to change, and to what?

**Comment by natebosch** [comment]
To be clear - we're talking about outputting that format?

Definitely should, we'll need to make sure we're ready for the SDK constraint to get that high.

cc @kevmoo - any reason not to do this now?

**Comment by kevmoo** [comment]
It'll be supported officially in 1.25 - https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md

Surprised that `package:` support is allowed for `part of`. Really, @matanlurey ?

**Comment by matanlurey** [comment]
I'm not sure, maybe it is just relative URLs.

@natebosch @kevmoo See https://github.com/dart-lang/source_gen/pull/158, which adds a way to do this in a backwards-compatible way. I don't think there is a way to auto-detect your SDK version though.

**Comment by kevmoo** [comment]
...and it's the dance between the version of the SDK running the generator, the target SDK for the package into which the code is being generated...and the version pkg/analyzer running behind source_gen.

Fun!

**Comment by matanlurey** [comment]
I suspect we should make this a flag on the `GeneratorBuilder` @kevmoo:

```dart
class GeneratorBuilder {
  GeneratorBuilder(this.generators, {bool requireLibraryDirective: true, ...})
}
```

Users that want to set a constraint of `>=1.25.0` can set this flag to `false`.

We can default it to `true` in a future release. WDUT?

**Comment by kevmoo** [comment]
SGTM – @jakemac53
