### ISSUE TITLE
Add 'findType', like 'LibraryElement.getType' but...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#160]
... includes walking `export` directives.

Open for alternative names, or closing this bug if there is something I'm missing.

**Comment by natebosch** [comment]
I like `findType(LibraryElement, String)` as a utility method in this package.

We could consider adding it to Resolver directly - but I like the idea of keeping that class narrow and building up utils here.

**Comment by matanlurey** [comment]
Me too. Based on my new definition of `source_gen`, I'd rather keep `build` to be super-small and stable long-term, while new techniques and utilities go here instead. I'll send a PR.
