### ISSUE TITLE
Subsequent builds after a failure give a "success" status.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/source_gen#162]
You can repro this on the example in this package, add a throw into the JsonSerializableGenerator and then run `dart tool/build.dart` a couple times. You get an error initially but then you get success because the file was written successfully and nothing has changed since (its a no-op build effectively).

It could be argued that this is an error in `package:build`, specifically that any `severe` log message should fail the build.

**Comment by natebosch** [comment]
Relevant: https://github.com/dart-lang/build/issues/215

I agree that a `log.severe` should fail the build, I don't think we should need to handle it in this package.

**Comment by jakemac53** [comment]
sgtm, I will close this one
