### ISSUE TITLE
Add helpers for interacting with constants/DartObject

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#169]
In `AngularDart` @alorenzen produced a number of `coerceX` methods (i.e. `coerceBool`), because we quickly found out that `DartObject#getField` rarely returns what you want - it only reads a constant fields _directly_ from the class (not delegating to `super.`).

I'd like to add them to this library, but not sure of the form. Some options:

* As-is (`coerceBool`, `coerceInt`, so-on)
* With a more descriptive name - i.e. `readFieldBool`
* Some sort of const-object wrapper, i.e.

```dart
abstract class Constant {
  factory Constant(DartObject obj) => ...

  bool get isBool;

  bool readBool({bool defaultTo()};
}
```

Thoughts? @jakemac53 @natebosch @kevmoo @alorenzen

**Comment by jakemac53** [comment]
We could also add to this class helper methods to get an actual instance (only throws if you are not importing the required types), or get as a String the code to recreate the constant?

**Comment by matanlurey** [comment]
Definitely! I'm going to take this as a "sure, let's do it". 

Do you have a preference on class wrapper versus top-level methods?

**Comment by jakemac53** [comment]
I think a wrapper makes the most sense.

**Comment by alorenzen** [comment]
+1 to class wrapper
