### ISSUE TITLE
Create a helper for a LibraryElement (Library)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#170]
Similar to https://github.com/dart-lang/source_gen/issues/169, it actually might be better to move `findType` to be a method of a helper called `Library` that wraps `LibraryElement`, versus polluting a bunch of top-level methods.

WDUT @jakemac53?

**Comment by jakemac53** [comment]
It sounds logical, but I do fear a bit that we are going to fall into a trap of creating wrappers for all core concepts now hahaha (Class, Directive, etc etc etc)

**Comment by matanlurey** [comment]
I think we can push back from most other requests, `LibraryElement` and `DartObject` are the two places I know of that are pretty complicated to use correctly while doing static analysis. We already have a `ClassElement` wrapper called `TypeChecker` ;)
