### ISSUE TITLE
Release v0.5.9

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#174]
@matanlurey @jakemac53 – I created a v0.5.9 milestone.

I'd love to get these bits out – just to use my JSON serializable silly.

Any other work we want to roll up into this release? – please tag PRs and issues accordingly...

**Comment by matanlurey** [comment]
@kevmoo This is likely ready to release!

**Comment by kevmoo** [comment]
Fixed with 494e0e7153a9786c61988b7507de2e3265e848c6
