### ISSUE TITLE
"library" check in 0.5.9 is a breaking change

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/source_gen#188]
Hi @matanlurey,

This change in 0.5.9 broke built_value:

```
Failing to add a library directive to a library that is being used as a
generator target that generates partial files (part of) is now an explicit
error that gives a hint on how to name and fix your library...
```

The problem is that it checks for a "library" statement even in files that the generator ends up ignoring. To not be a breaking change, it needs to only do the check when a ".g.dart" file ends up being created -- i.e. where it would already have been an error.

Possible fixes:

1. Improve the check so that it only applies when an output is generated. Not sure how easy this is.
2. Make the new check off by default.
3. Roll back and re-release in a 0.6 version to indicate the breaking change.

<span>#</span>1 looks like the best fix if it's possible.

What do you think, please?

@kevmoo @jakemac53

**Comment by jakemac53** [comment]
#1 looks like the best to me, #3 isn't the ideal solution either way imo.

**Comment by matanlurey** [comment]
We can fix the check and release 0.5.9+1

**Comment by kevmoo** [comment]
Open for a pull request 😄

**Comment by kevmoo** [comment]
@matanlurey fixed by https://github.com/dart-lang/source_gen/commit/ce4b5842de2f123cc5cf7147664280ee44e9cf0f, right?

**Comment by matanlurey** [comment]
Yep!

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/source_gen/commit/ce4b5842de2f123cc5cf7147664280ee44e9cf0f

**Comment by davidmorgan** [comment]
Could you let me know when this hits pub so I can rerun the built_value travis, please?

Thanks!
