### ISSUE TITLE
Add a package:matcher for TypeChecker

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#197]
/cc @kevmoo and @jakemac53 - as I don't know you feel about adding `package:matcher` as a dependency. We could do `source_gen_test`... but blargh. I'd like to be able to write:

```dart
test('...', () {
  expect(aComponent, isExactly(componentTypeChecker));
});
```

**Comment by jakemac53** [comment]
It might be best to wait a bit and see how https://github.com/dart-lang/pub/pull/1647 goes?

**Comment by natebosch** [comment]
+1 on waiting for features or pulling out package:source_gen_test.

**Comment by matanlurey** [comment]
I'm happy to skip this for now.
