### ISSUE TITLE
TypeChecker.exactMatchAnnotationsOf

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#199]
/cc @kevmoo for thoughts.

Basically, something like:

```dart
$Foo.annotationsOf(someElement, andAssignable: true);
```

Or we could make this the default behavior, and add `onlyExact: true`. WDUT?

**Comment by natebosch** [comment]
What's the use case for `onlyExact`? Seems to me we'd always be interested in assignable?

**Comment by matanlurey** [comment]
Angular specifically, at least right now, doesn't want to match sub-classes of `@Component`.

**Comment by natebosch** [comment]
Ah ok sounds good.

I think it'd be nicer to have two separate methods rather than a method with a boolean argument.

I'm fine with either `annotationsOf` and `exactMatchAnnotationsOf` or `annotationsOf` and `assignableAnnotationsOf` depending on which we think is more common.

**Comment by matanlurey** [comment]
That works for me! It's a FR.
