### ISSUE TITLE
LibraryReader#urlForElement

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#205]
Similar to https://github.com/dart-lang/source_gen/pull/172, but takes an `Element`:

```dart
String urlForElement(Element e);
```

The reason I want this is to be able to "import" the user-visible API, instead of potentially something buried in "src/blah/foo/blah.dart". For example, I'd want the `Component` class in AngularDart to return `angular/angular.dart`, not `angular/src/core/metadata.dart`.

Does that make sense?

/cc @jakemac53 @kevmoo @natebosch

**Comment by matanlurey** [comment]
Here is my naive implementation:

```dart
  String urlForElement(Element element) {
    _urlCache ??= <String, String>{};
    return _urlCache.putIfAbsent(element.name, () {
      return _namespace.get(element.name).library.source.uri.toString();
    });
  }
```

**Comment by natebosch** [comment]
Sounds like a good idea, we'd have to be careful about what promises we make - I imagine there are a lot of edge cases here?

Also I don't think we can rely on `element.name` being unique can we?

**Comment by matanlurey** [comment]
@natebosch: PTAL again. Yeah I haven't tried to tackle prefixed elements :-/. Any ideas?

**Comment by natebosch** [comment]
Looks pretty good. I'm not sure of some of the global variables but assuming this all works I think it's worth having in this package.

**Comment by matanlurey** [comment]
I sent it over the analysis folks to see if they have any ideas for prefixed elements.

**Comment by matanlurey** [comment]
@scheglov and @bwilkerson seemed to think it was possible, but not how I'm doing it (i.e. this doesn't account for `as` or `show`/`hide` correctly).

Does it make sense to iterate on something here?

**Comment by natebosch** [comment]
If angular would use it I'd say we can push on it, otherwise we could put it on hold until we have a better idea what the future analyzer api looks like

**Comment by matanlurey** [comment]
Definitely can start using it _relatively_ soon. I can keep it in Angular though until it's stable.

**Comment by matanlurey** [comment]
Closing for now.
