### ISSUE TITLE
Make "normalizeUrl" public.

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#211]
... otherwise I need to write identical APIs in AngularDart. It seems stable enough:

https://github.com/dart-lang/source_gen/blob/master/lib/src/utils.dart#L93

**Comment by natebosch** [comment]
What is the usage of a URI one it is normalized? Is it for canonicalization? If so can we use AssetId instead?

**Comment by natebosch** [comment]
I suppose dart: URI can't be turned into an AssetId?

**Comment by matanlurey** [comment]
Probably can use `AssetId`, yeah for canonicalization, but it needs to work for `dart:` too.

**Comment by matanlurey** [comment]
I mean if you're OK with saying `AssetId` can represent a Dart SDK file then works for me :)

**Comment by natebosch** [comment]
`normalizeUrl` doesn't look like it handles relative URIs - do we need it to?

**Comment by matanlurey** [comment]
Decided to close this for now until we need it outside of AngularDart.
