### ISSUE TITLE
ConstantReader#peek

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#214]
In contrast with `read`, `peek` should return a `null` value instead of throwing an exception if a field is not found. This allows a more graceful way of checking for this first non-null value, for example:

```dart
findTokenField(DartObject o) {
  final reader = new ConstantReader(o);
  final token = o.peek('token') ?? o.peek('_token');
}
```

Other options:

1. Add an `Function<Object> orElse` parameter to `read`.
2. Add an explicit way to read/check many parameters, i.e.

```dart
final token = o.read('token', '_token'); 

// or

final token = o.readFirst(['token', '_token']);
```

**Comment by matanlurey** [comment]
3rd-option: Add `has`:

```dart
if (o.has('token')) {
  // ...
} else if (o.has('_token')) {
  // ...
}
```

**Comment by zoechi** [comment]
What about `o.read('token', orElse: (e) => null)` like it's done in other SDK APIs?

**Comment by natebosch** [comment]
Consistency with existing APIs is a very strong argument.
I think, though, that most of those were written before `??` existed and I don't think `orElse` composes as nicely... Compare:

```dart
var x = reader.read('foo', orElse: () => reader.read('bar', orElse: () => 'default'));
```

with

```dart
var x = reader.peek('foo') ?? reader.peek('bar') ?? 'default';
```

I can't think of any places where `orElse` is easier to read that `peek` + `??` - but if we find such a place we can definitely revisit this.

**Comment by zoechi** [comment]
I see. Thanks for explaining the reasoning.
