### ISSUE TITLE
Make all members of `GeneratorBuilder` (or whatever it ends up getting called) private

### ISSUE THREAD

**Issue by natebosch** [dart-lang/source_gen#219]
Currently things like `generatedExtension` and `generators` are public, but we should probably keep the interface to that of `Builder` unless we find a use case for reading something else externally. We don't want to handcuff ourselves to more breaking changes if we tweak the implementation.

**Comment by natebosch** [comment]
Also probably make the typedef for the formatter private.

**Comment by kevmoo** [comment]
...new function syntax FTW!

**Comment by natebosch** [comment]
When can we start using new function syntax? Is it fully available in `1.24`? Do we feel OK setting our SDK constraint that high?

**Comment by matanlurey** [comment]
Fully available in 1.24. Angular has that restriction FWIW.
