### ISSUE TITLE
Remove ability to instantiate annotations

### ISSUE THREAD

**Issue by natebosch** [dart-lang/source_gen#224]
Instead of passing a `T` we could pass a `DartObject` which we guarantee (using the type matcher) will represent a `T`.
The API for using it is not as nice (`.getField('name')` instead of `.name`) but it would mean we don't have a contract we can't always satisfy and it makes the code simpler.

I'm not completely convinced we should do this, but it's worth discussing. There has been talk about getting more reliable instantiation from `DartObject` in the analyzer itself - but this hasn't gone anywhere and is unlikely to for a while, so I'm not sure we should bank on it.

cc @kevmoo @jakemac53

**Comment by matanlurey** [comment]
Of course you can use `ConstantReader` to make it a little nicer to read from :)

**Comment by natebosch** [comment]
Good call - was just looking over that api 😄

**Comment by matanlurey** [comment]
I'd be supportive of adding a `[]` operator to it for something like:

```dart
reader['foo.bar.title'] // String
```
