### ISSUE TITLE
Add optional arg to skip unresolved annotations for TypeChecker methods

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/source_gen#248]
Specifically, the following apis will get a `bool skipUnresolvedAnnotations` optional parameter:

`TypeChecker#firstAnnotationOf`,
`TypeChecker#firstAnnotationOfExact`
`TypeChecker#annotationsOf`
`TypeChecker#annotationsOfExact`

This allows you to use the `TypeChecker` in a partially resolved world to match annotations for which you do have resolved type information.

**Comment by natebosch** [comment]
Let's call it `skipUnresolved` since `Annotation` is already known by context.

**Comment by matanlurey** [comment]
👍

**Comment by jakemac53** [comment]
Actually, how about `throwOnUnresolved`? It is a bit more explicit about the failure case I think.
