### ISSUE TITLE
strategy to work with WebStorm/IntelliJ

### ISSUE THREAD

**Issue by sethladd** [dart-lang/source_gen#27]
IntelliJ/WebStorm don't use build.dart. Let's deliver something that gives our sublime friends an edit-gen cycle, without asking them to manually run build.dart.

**Comment by dikmax** [comment]
WebStorm has File Watchers. I use them to automatically call build.dart on code change. Very convenient.

**Comment by a14n** [comment]
You can also use my [build_system](https://pub.dartlang.org/packages/build_system) package to automatically call `build.dart`.

**Comment by matanlurey** [comment]
@kevmoo I'm assuming we can close this since `watch.dart` was introduced (and it also looks like the community has contributed at least one concept?)

**Comment by kevmoo** [comment]
Yup
