### ISSUE TITLE
analyzer not updated for 2nd builder

### ISSUE THREAD

**Issue by zoechi** [dart-lang/source_gen#273]
I have a built_value class

![image](https://user-images.githubusercontent.com/405837/30476326-faa1d088-9a09-11e7-9084-271ebf902edb.png)

and build it with 
```dart
/// builder phases for built_value
List<BuildAction> phases() => [
      new BuildAction(
          new PartBuilder([
            new BuiltValueGenerator(),
            new BuiltReduxGenerator(),
          ]),
          'my_proj_shared',
          inputs: const ['lib/**/*.dart'])
    ];
```

In the `BuiltReduxGenerator` I get

![image](https://user-images.githubusercontent.com/405837/30476342-051f5026-9a0a-11e7-9854-7e3f4c11dee3.png)

instead of
```dart
ActionDispatcher<Thunk<RxApp, RxAppBuilder, RxAppActions>> get request;
```
I get
```dart
ActionDispatcher<Thunk<RxApp, dynamic, RxAppActions>> get request;
```
Is there something I can do, or is this a bug/missing feature?

**Comment by zoechi** [comment]
I haven't found a workaround.
Using the string doesn't work because it resolves the function typedef and makes it unusable for this purpose

![image](https://user-images.githubusercontent.com/405837/30476699-13b2d56c-9a0b-11e7-938e-a59c087a1f7f.png)

**Comment by natebosch** [comment]
All the generators in the same part builder run concurrently, they can't resolve the code output by each other. In order to resolve the build value code in the other generator it will need to be in a different build action, which also means it'll need to output a different file

**Comment by zoechi** [comment]
I see. Thanks for the info.
In the meantime I found a way to get the name of a typedef type parameter.
