### ISSUE TITLE
A generic way to add common headers (copyright) to all generated files

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#275]

**Comment by kevmoo** [comment]
Thoughts @jakemac53 @natebosch ?

**Comment by zoechi** [comment]
and linter `// ignore_for_file: ...` comments

**Comment by jakemac53** [comment]
Seems reasonable to me! Could add a `header` field to `Generator` as one option.

**Comment by kevmoo** [comment]
> Seems reasonable to me! Could add a header field to Generator as one option.

But what about multiple generators running on one file?

Forgive the crazy – almost want an option for an `all file` generator that runs over...well, all generated files. Make it not a real generator – let folks provide a function that takes in a path (String) and returns a String (header content) or null/empty

**Comment by jakemac53** [comment]
There are already some similar fields on `GeneratorBuilder`, what if we just add it there? At that point only the provided generators can run (it controls the output file).

**Comment by natebosch** [comment]
+1 on adding this as an argument to `PartBuilder` and `LibraryBuilder`

**Comment by kevmoo** [comment]
Yes!
