### ISSUE TITLE
element.documentationComment is always null in GeneratorForAnnotation<>

### ISSUE THREAD

**Issue by alex-aprm** [dart-lang/source_gen#279]
Cannot access method or class documentation, because "element.documentationComment" property is always null for all elements.

**Comment by natebosch** [comment]
I'm seeing the same thing.

@bwilkerson - do you know when the `documentationComment` will or won't be populated in the Element model?

We're using `AnalysisContext` - [here](https://github.com/dart-lang/code_transformers/blob/master/lib/src/resolver_impl.dart#L61) is where we configure it.

I can share a repro going through our build system if it would help.

**Comment by matanlurey** [comment]
Closed in favor of https://github.com/dart-lang/build/issues/642.

This repository specifically doesn't have anything to do with analysis.
