### ISSUE TITLE
Model grouping class generation within a single (abstract?) class

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#28]
You could imagine generators for a class: json, equality, sorting, toString, etc

Would be nice if these could be coordinated across generators and populated within class.

**Comment by matanlurey** [comment]
Do we still want this here in `source_gen`?

**Comment by jakemac53** [comment]
+1 to closing this issue, seems more trouble than its worth.

**Comment by kevmoo** [comment]
We could imagine a roll-up generator that coordinates this – but it should be at a higher level than source_gen
