### ISSUE TITLE
Add option to omit null fields from fromJson constructor

### ISSUE THREAD

**Issue by AlexanderJohr** [dart-lang/source_gen#280]
Great Library. Finally something to replace Dartson with. However: When deserializing fields that aren't in the json, I get errors like "boolean expression must not be null". I would like to keep the default values assigned to the fields instead of having those overwritten by null.

**Comment by matanlurey** [comment]
I think you're now looking for https://github.com/dart-lang/json_serializable?

**Comment by AlexanderJohr** [comment]
Yes, I came here via the issue #104 by searching for "jsonserializable dartlang" and thought I would be in json_serializable.

I moved the issue it to the right repository: https://github.com/dart-lang/json_serializable/issues/75
