### ISSUE TITLE
TypeChecker: Support nested generics

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#284]
`TypeChecker.fromUrl` is a really nice syntax for pointing to a specific type:
https://github.com/dart-lang/source_gen/blob/5c28bd17528dcc47c48f09ab636736d29be8bc7a/lib/src/type_checker.dart#L53

For example:

```dart
// Can now use to do checks.
const dartCoreString = const TypeChecker.fromUrl('dart:core#String');
````

It's currently not supported to refer to generic types, but (a) I'll need this in AngularDart and (b) I've started using this `Uri` format elsewhere in other projects related to code generation/analysis, and it falls short here.

In this case, how should we refer to `List<String>`?

1. Contrive some URL-based solution

For example, something like `dart:core#List<dart:core#String>`. An obvious upside is you can continue just to use `Uri.parse` and `toString()`, but that means that `TypeChecker` (and other tools) will have to do more work, potentially in duplicate manners.

2. Create some sort of TypeReference (name?) value type

```dart
abstract class TypeReference {
  Uri get type;
  List<TypeReference> get typeArguments;
}
```

3. ?????

**Comment by natebosch** [comment]
I like the non-URI approach. I would prefer not to get into the business of parsing nested `<>`

**Comment by matanlurey** [comment]
That's my feeling as well. 

Another question is how the user API will be made available.

1. Just do a untyped list, where `dynamic` could be `Uri`, `String`, or `TypeReference`.

```dart
factory TypeChecker.fromUrl(dynamic url, [List<dynamic> typeArguments])
```

2. Always require a `TypeReference`:

```dart
factory TypeChecker.fromReference(TypeReference reference);
```

We could deprecate `fromUrl`, or keep it for convenience with non-generic classes. WDUT?

**Comment by natebosch** [comment]
Yeah I think I like allowing `dynamic` to be `Uri`, `String`, or `TypeReference`.

```dart
factory TypeChecker.fromUrl(dynamic url, [List<dynamic> typeArguments]);
factory TypeReference(dynamic url, [List<dynamic> typeArguments]);

/// List<String>
var listOfStringA =
    new TypeChecker.fromUrl('dart:core#List', ['dart:core#String']);

/// List<Map<String, int>>
var listOfMaps = new TypeChecker.fromUrl('dart:core#List', [
  new TypeReference('dart:core#Map', ['dart:core#String', 'dart:core#int'])
]);
```

We could add `TypeChecker.fromReference` for convenience too.

**Comment by matanlurey** [comment]
Sgtm!

**Comment by matanlurey** [comment]
Oof. This is much harder than I thought.

It is ~trivial to create the checker, but very hard to implement it. For example, checking if something *is* a `List<String>` isn't too hard, but checking if something is _assignable_ to say. `Iterable<Comparable>`? Legitimately hard.

Unless someone sees something I'm missing I might need to sit on this for a while.

**Comment by natebosch** [comment]
This is relatively easy to support with `factory TypeChecker.fromStatic(DartType type)` right?

Maybe we should deprecate `fromRuntime` and see if we can find a way to get from a Url to a `DartType`?

**Comment by matanlurey** [comment]
Yeah, but it gets tricky here too - how do you "make" an `Iterable<String>` for example?

**Comment by natebosch** [comment]
Hmm, yeah I'm not sure.

The hack approach is check in some code with an instance of `Iterable<String>` in it with a known location and ask for it's `DartType` when you need to reference it. But that might only work if the code is transitively imported from whatever you're operating on...

**Comment by matanlurey** [comment]
Closing for now, might iterate on this within Angular for the time being.

**Comment by matanlurey** [comment]
Looks like it will be best to have this within source_gen, because again, it is brittle.

**Comment by matanlurey** [comment]
Closing again, for now.
