### ISSUE TITLE
Revert prefixFor feature(s).

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#292]
This is code that is super tough to get right, and I imagine most of the time most generators that use part files just disallow using prefixes to import code because of it. In AngularDart we still need to support this right now, and our code is brittle.

Adding this feature would also make analyzer changes more visible.

```dart
class LibraryReader {
  /// Returns the identifier prefix if [element] is referenced by one.
  ///
  /// For example in the following file:
  /// ```dart
  /// import 'bar.dart' as bar;
  ///
  /// const b = const bar.Bar();
  /// ```
  ///
  /// If there is no prefix, one could not be computed, or the [element] is
  /// in a library different from the current one this will return `null`.
  String prefixFor(Element element);
}
```

`prefixFor` could return `bar` for the top-level field `b`.

Other considerations:
* [ ] If the element is outside the current library, always return `null`. This consideration is important because in implementations such as `bazel_codegen`, the underlying function we will need to use, `computeNode()`, fails on files provided only by summaries.

/cc @natebosch to spot check this feature's acceptability :)
/cc @MichaelRFairhurst who helped me identify why this fails in Angular (summary file)

**Comment by natebosch** [comment]
Sounds like a good feature.

> `prefixFor` could return `bar` for the top-level field `b`.

Hmm, the field doesn't have a prefix does it? It makes sense to me that the `ClassElement` for `Bar` would return a prefix of `'bar'` - but I don't understand why `b` would be considered to have a prefix.

> If the element is outside the current library, always return `null`

I think we should throw instead since `null` means 'no prefix'

**Comment by matanlurey** [comment]
I've decided to revert this feature, and remove it.

It's not trivial to support in future source-generation models.
