### ISSUE TITLE
Add "getTypeName"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#294]
... basically this:
https://github.com/dart-lang/angular/blob/ebdf71ee67efa6f0765afcef3959ca469639111f/angular_compiler/lib/src/analyzer/common.dart#L9-L24

... which is required because the newer models of the analyzer don't have the name of a `typedef`.

/cc @natebosch

**Comment by matanlurey** [comment]
Suggestions open for a better name than `getTypeName`

**Comment by natebosch** [comment]
`typeNameOf(DartType type)`

It kind of sucks though. Could we file an issue against the analyzer to return a non-null name here?

**Comment by matanlurey** [comment]
> Could we file an issue against the analyzer to return a non-null name here

We _could_, but unfortunately it won't be a priority until the CFE-ication is complete.
