### ISSUE TITLE
Bump analyzer version

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/source_gen#304]
If I understand correctly we need `0.31.0-alpha.1` to avoid the analyzer throwing when it encounters the new function syntax. This is making it hard to upgrade `built_value` to the latest `build_runner`.

So ... can we bump source_gen to `0.31.0-alpha.1`? Happy to send a PR if it's a straightforward change.

Thanks.

**Comment by natebosch** [comment]
We'd need to update at least:

- [source_gen](https://github.com/dart-lang/source_gen/blob/19a33605da392d11490f86bccc11a606c7e5be94/pubspec.yaml#L9)
- [build](https://github.com/dart-lang/build/blob/3bc25db1418950898f1e9ed7b156a5413b76b681/build/pubspec.yaml#L11)
- [build_barback](https://github.com/dart-lang/build/blob/3bc25db1418950898f1e9ed7b156a5413b76b681/build_barback/pubspec.yaml#L11)
- [build_runner](https://github.com/dart-lang/build/blob/3bc25db1418950898f1e9ed7b156a5413b76b681/build_runner/pubspec.yaml#L11)

We have avoided this because we aren't sure we want non-alpha releases of these packages depending on alpha releases of the anlayzer.

**Comment by davidmorgan** [comment]
Yeah, this is awkward. 

When trying to bump the `build_runner` (and hence, SDK) version for `built_value` I hit a problem which I believe is due to the use of the new Function syntax here:

https://github.com/dart-lang/test/blob/master/lib/src/backend/invoker.dart#L36

I worry that we're going to get more and more breakage as the new Function syntax creeps into more packages. My understanding is that the only fix is to be on the latest SDK and analyzer, but maybe I misunderstood?

Thanks.

```
[SEVERE] Build: Failed after 9.9s
AnalysisException: Cannot compute LIBRARY_ELEMENT for Instance of 'AssetBasedSource'
Caused by Unexpected exception while performing ResolveUnitTypeNamesTask for source test|lib/src/backend/invoker.dart
...
Caused by NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9944:19)
```

**Comment by matanlurey** [comment]
@kevmoo Is it reasonable to get a new (stable) version of the analyzer?

**Comment by kevmoo** [comment]
Not likely

**Comment by natebosch** [comment]
cc @nex3, @grouma 

Would it be feasible to bump the package:test dependency on analyzer to 0.31.0-alpha.1?

If we bump the deps throughout the `build` packages our end users would still need a `dependency_override` to use it alongside `test`

**Comment by natebosch** [comment]
Synced offline, the test upper bound is `<0.32.0` which should cover `0.31.0-alpha.1` so I think it's just the build packages that need to be updated

**Comment by davidmorgan** [comment]
My intuition is that this would fit with making packages explicitly target the Dart 2 dev version of the SDK. I guess we're going to have to release versions of the packages before Dart 2 hits stable ... it doesn't seem too bad to also depend on unstable analyzer at the same time.

Thoughts?

Thanks.

**Comment by matanlurey** [comment]
I think @kevmoo and friends are rolling on this now.

**Comment by matanlurey** [comment]
Actually, I'll help out here!

**Comment by matanlurey** [comment]
Ah, was actually done as of https://github.com/dart-lang/source_gen/commit/0a42d2081c691addb19c83a49601a8583475313a#diff-fb2d52cd953afedcafc9fe7629c6f132.

**Comment by kevmoo** [comment]
I'm handing off responsibility to migrate the rest of the build_* packages
and angular to SWEs :-)
