### ISSUE TITLE
Flip and deprecate "requireLibraryDirective"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/source_gen#309]
... since I imagine we want to make this package based on Dart2.

https://github.com/dart-lang/source_gen/blob/baa15b66093c17d61fb2bf67a75bf1d19f71d5f2/lib/src/builder.dart#L181

**Comment by natebosch** [comment]
One thing to keep in mind - the SDK constraint on this package limits what SDK can be used to _generate_ the code. It does not limit what SDK can be use to _run_ the code.

Unless we're checking that the package we're generating code in also has an SDK constraint of 2.0.0-dev we're potentially generating code that could be published but not run.

**Comment by matanlurey** [comment]
True, but you could do that today by using function types in generated code.

**Comment by kevmoo** [comment]
Yup. The trick is making sure to not change the current behavior when a library declaration exists.

Trying to figure that out now...

**Comment by matanlurey** [comment]
Yeah, I think that is fair. If they wrote a library directive, use it.

**Comment by kevmoo** [comment]
Fixed in https://github.com/dart-lang/source_gen/pull/310/commits/5798781f4e58f4ef8b2abd897391e323441cd435

published as 0.7.5

**Comment by kevmoo** [comment]
FYI – this has been flipped everywhere, including json_serializable.

Trailing bit: https://github.com/dart-lang/pub-dartlang-dart/pull/978

Thanks for pointing this out, @matanlurey !
