### ISSUE TITLE
Add a CombiningBuilder for .g.dart files and document how to use it

### ISSUE THREAD

**Issue by natebosch** [dart-lang/source_gen#319]
We added `runs_before` and `applies_builder` to build config so it should be possible now to put everything together with one or more source_gen part builders cooperating to generate a single part file. We'll want a "CombiningBuilder" ("MergingBuilder"?) in this package to read in all the files generated by different part builders and write them to a single output.

- [x] Fix duplicate headers - https://github.com/dart-lang/source_gen/pull/348
- [x] Fix logging of missing `part` directive - https://github.com/dart-lang/source_gen/pull/348
- [x] Document usage in readme
- [x] Update `build.yaml` to properly expose `CombiningBuilder`
- [x] **BLOCKING** Get build issue fixed related to running built-to-cache builder over transitive dependencies - https://github.com/dart-lang/build/issues/1578
- [x] Add a cleanup builder

After published...
- [x] Add a working example to `repo/example`

**Comment by kevmoo** [comment]
@grouma – added some work items before we can close this. The first two are handled by my pending PR

**Comment by kevmoo** [comment]
How are we doing w/ the check boxes here @natebosch and @grouma ?

**Comment by kevmoo** [comment]
...still need to tweak build.yaml, right?

**Comment by natebosch** [comment]
> ...still need to tweak build.yaml, right?

I think it looks correct (other than a nit about single vs double quotes). README and example are the remaining issues. I wanted also to validate usage which is what https://github.com/dart-lang/json_serializable/pull/260 is meant to accomplish.

**Comment by kevmoo** [comment]
ack

**Comment by natebosch** [comment]
yes, I think we are safe to publish now. @grouma, @jakemac53 - can you think of anything else blocking?

**Comment by jakemac53** [comment]
I haven't been following this to closely :grimacing: but nothing blocking I am aware of.

**Comment by kevmoo** [comment]
Version bumb to v1 first?

**Comment by grouma** [comment]
Should be good to go.

**Comment by natebosch** [comment]
There's an example now, I think we've finished.
