### ISSUE TITLE
Support incremental generations

### ISSUE THREAD

**Issue by a14n** [dart-lang/source_gen#33]
I like to be able to have a source like

``` dart
@Value()
abstract class _MyClass {
  String a, b;
}
```

The generator for `ValueClass` whould generate:

``` dart
@DefaultConstructor()
@EqualsAndHashCode()
@ToString()
@ToConcretPublicClass()
abstract class _MyClass {
  String a, b;
}
```

Then the generated part would be re-analyzed and the generator for `DefaultConstructor` would generate:

``` dart
@EqualsAndHashCode()
@ToString()
@ToConcretPublicClass()
abstract class _MyClass {
  String a, b;
  _MyClass({this.a, this.b});
}
```

Next round with  the generator for `EqualsAndHashCode`:

``` dart
@ToString()
@ToConcretPublicClass()
abstract class _MyClass {
  String a, b;
  _MyClass({this.a, this.b});
  @override int get hashCode => hashObjects([a, b]);
  @override bool operator ==(o) => identical(this, o) || o.runtimeType == runtimeType && o.a == a && o.b == b;
}
```

Next round with  the generator for `ToString`:

``` dart
@ToConcretPublicClass()
abstract class _MyClass {
  String a, b;
  _MyClass({this.a, this.b});
  @override int get hashCode => hashObjects([a, b]);
  @override bool operator ==(o) => identical(this, o) || o.runtimeType == runtimeType && o.a == a && o.b == b;
  @override String toString() => "_MyClass(a=$a, b=$b)";
}
```

Next round with  the generator for `ToConcretPublicClass`:

``` dart
class MyClass {
  String a, b;
  MyClass({this.a, this.b});
  @override int get hashCode => hashObjects([a, b]);
  @override bool operator ==(o) => identical(this, o) || o.runtimeType == runtimeType && o.a == a && o.b == b;
  @override String toString() => "MyClass(a=$a, b=$b)";
}
```

This issue is a little related to #28

**Comment by kevmoo** [comment]
I like the idea that Generator Q really just proxies to Generator A, B, C...

We'll probably do it that way instead of having multiple iterations. I don't want generators running over generated code.

**Comment by a14n** [comment]
I cannot see how to make several changes to the same class when the output of a generator is a simple `String` ? That's why I came up with the incremental generation.

I first thought about an API to modify the Element but it can become quickly complex and perhaps less simple and powerfull compared to incremental generations (like Java APT does).

**Comment by kevmoo** [comment]
Java APT? Could you include a pointer? Always happy to learn more.

**Comment by a14n** [comment]
I don't find a simple and clear article on the subject but I think @peter-ahe-google can give you some informations ;) .

```java
package javax.annotation.processing;
/**
 * [...]
 * @author Joseph D. Darcy
 * @author Scott Seligman
 * @author Peter von der Ahé
 * @since 1.6
 */
public interface Processor {
```

Basically it allows to process sources at compile time. The main method of the processor returns a `boolean` to indicate that the current processing step has created new files that need to be processed once again in a new phase. Once all the generators return false it's done.

**Comment by a14n** [comment]
The javadoc of [Processor](http://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Processor.html) has some informations.

**Comment by greglittlefield-wf** [comment]
I've run into a similar issue, where code from one generator depends on the output of another generator.

For example, a library:
```dart
//
// my_library.dart

library my_library;

@GenerateType
abstract class _MyType {}

@GenerateTypedMapView
abstract class _DependentClass {
  MyType get myValue; // `MyType` doesn't exist just yet
}
```
with a build call of the following:
```dart
await build(args, [
  const TypeGenerator(),
  const TypedMapViewGenerator()
], librarySearchPaths: ['lib']);
```
would generate something like this:
```dart
//
// my_library.g.dart (current)

part of my_library;

class MyType {
  String toString() => "I'm a real class of type 'MyType'!";
}

class DependentClass extends MapView {
  // The analyzer resolved the returnType of `_DependentClass.myValue` to `dynamic` since `MyType` wasn't defined yet.
  dynamic get myValue => this['myValue'];
  set myValue(dynamic value) => this['myValue'] = value;
}
```

---

If it were possible to output generation to a specified file or part, then you could utilize generated output in subsequent generators:

```dart
// Generate types first so that they're available for analysis when MapViews are generated
await build(args, [
  const TypeGenerator()
], librarySearchPaths: ['lib'], outputName: 'generated_types');

await build(args, [
  const TypedMapViewGenerator()
], librarySearchPaths: ['lib'], outputName: 'generated_map_views');
```

```dart
//
// my_library.generated_types.g.dart

part of my_library;

class MyType {
  String toString() => "I'm a real class of type 'MyType'!";
}
```
```dart
//
// my_library.generated_map_views.g.dart

part of my_library;

class DependentClass extends MapView {
  // `MyType` was resolved!
  MyType get myValue => this['myValue'];
  set myValue(MyType value) => this['myValue'] = value;
}
```

**Comment by matanlurey** [comment]
@jakemac53 Is this even possible with our build system restrictions?

**Comment by natebosch** [comment]
Similar to https://github.com/dart-lang/bazel/issues/151?

I suspect this may be more of a build_runner or bazel concern than source_gen
