### ISSUE TITLE
Ability to specify a directory(root) to place generated code

### ISSUE THREAD

**Issue by ferhatb** [dart-lang/source_gen#37]
Some source control systems require generated code to be rooted at separate path.

Example:
/source-repo/dartproject/lib/sourcefile.dart
/generated/dartproject/lib/sourcefile.g.dart

Strawman :
build(args, const [const MyGenerator()],
      librarySearchPaths: ['lib'] , repoPath: "/source-repo" , outputPath: "/generated");

**Comment by natebosch** [comment]
I think this is obsolete based on work customizing package:build for various build systems.
