### ISSUE TITLE
Generator is being called, but no file is generated

### ISSUE THREAD

**Issue by jorgecoca** [dart-lang/source_gen#381]
*Dart version:* Dart VM version: 2.1.0-dev.3.1.flutter-760a9690c2 (Wed Aug 29 07:29:38 2018 +0000) on "macos_x64"

----

I am facing an issue where I have a `GeneratorForAnnotation` being called during `pub run build_runner build`, but it is not generating the file. This is the code:

*build.yaml*:
```yaml
targets:
  $default:
    builders:
      cooper|cooper_generator:
        enabled: true

# Info for `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  cooper_generator:
    import: "package:cooper_generator/builder.dart"
    builder_factories: ["cooperGenerator"]
    build_extensions: {".dart": ["cooper_generator.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
```

*builder.dart*:
```dart
library copper_generator;

import 'package:build/build.dart';
import 'package:cooper_generator/src/cooper_generator.dart';
import 'package:source_gen/source_gen.dart';

Builder cooperGenerator(BuilderOptions options) =>
    SharedPartBuilder([CooperGenerator()], 'cooper');
```

*cooper_generator.dart*:
```dart
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'package:cooper/cooper.dart';

class CooperGenerator extends GeneratorForAnnotation<Cooper> {
  @override
  String generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) {
    final message = "// a test comment for ${element.name}";
    print(message);
    return message;
  }
}
```

When I call `pub run build_runner build --verbose`, this is what gets printed:
```
➜  example git:(master) ✗ pub run build_runner build --verbose
[INFO] Generating build script completed, took 311ms
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 82ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 353ms

[WARNING] BuildDefinition:
Invalidating asset graph due to build script update
[INFO] BuildDefinition:Cleaning up outputs from previous builds....
[INFO] BuildDefinition:Cleaning up outputs from previous builds. completed, took 3ms

[INFO] BuildDefinition:Building new asset graph...
[INFO] BuildDefinition:Building new asset graph completed, took 330ms

[INFO] BuildDefinition:Checking for unexpected pre-existing outputs....
[INFO] BuildDefinition:Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Build:Running build...
[FINE] cooper_generator on lib/main.dart:Running CooperGenerator
[FINE] cooper_generator on lib/placeholder_api.dart:Running CooperGenerator
[WARNING] cooper_generator on lib/placeholder_api.dart:
// a test comment for PlaceholderApi
[INFO] Build:Running build completed, took 551ms

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 46ms

[INFO] Build:Succeeded after 608ms with 1 outputs (5 actions)
``` 

What is wrong with this configuration? Thanks!

**Comment by jakemac53** [comment]
@jorgecoca the problem I think is related to the `build_extensions` in your builder - they are incorrect in the config (we don't have validation right now to ensure they match the actual builder).

The way that the `SharedPartBuilder` works it generates `.$partId.g.part` files and then the combing_builder merges those all into the `.g.dart` file. So, your build_extensions should look like `{".dart": [".cooper.g.part"]}`.

This matters because we do ordering based on that static config, the combining_builder has required inputs of `.g.part`, which makes it run after your builder (assuming it declares those files as outputs).

**Comment by jakemac53** [comment]
You could validate this by looking at your `.dart_tool/build/entrypoint/build.dart` file and checking the order of the builder applications there.

**Comment by jorgecoca** [comment]
Thanks for the advice! I have changed it, and I see a file being generated in `.dart_tool/build/entry_point/generated/example/lib/placeholder_api.cooper.g.part`, but shouldn't this create the autogenerated file in just `./example/lib/placeholder_api.g.dart`?

**Comment by jorgecoca** [comment]
Thanks for the advice! I have changed it, and I see a file being generated in `.dart_tool/build/entry_point/generated/example/lib/placeholder_api.cooper.g.part`, but shouldn't this create the autogenerated file in just `./example/lib/placeholder_api.g.dart`?

**Comment by jakemac53** [comment]
Your builder outputs the `.cooper.g.part` files to cache, because regular users shouldn't see them. The combining_builder should be creating the `.g.dart` file in the source tree where you describe.

If it isn't then its likely an ordering issue.

**Comment by jorgecoca** [comment]
Mistery solved! First problem I had was what you mentioned above; second problem was that I had this:

`build_extensions: {".dart": ["cooper_generator.g.dart"]}`

instead of:

`build_extensions: {".dart": [".cooper.g.part"]}` (dart <-> part) 🤦‍♂️ 

We can consider now this issue fixed!

**Comment by definev** [comment]
my generator name `vil_generators` which is order behind `source_gen:combining_builder` how can I resolve that?
