### ISSUE TITLE
LibraryReader.classElements should include enums

### ISSUE THREAD

**Issue by simolus3** [dart-lang/source_gen#388]
The iterable obtained from `LibraryReader.classElements` does not contain enum classes defined in the respective compilation unit. Given that enums are also represented with a `ClassElement` from the analyzer, I would expect them to be included.
I see that the documentation specifically points out that `class` elements defined in the library will be returned, but I think that this makes the name `classElements` a bit confusing. Perhaps there should be a getter `classes`, one for `enums` and one for both?

**Comment by natebosch** [comment]
I think it could be considered breaking to start including enums in the result for `classElements`. I like the idea of splitting them but I think we might skip on having a single getter that returns both. You can get that with: `libraryReader.classes.followedBy(libraryReader.enums)`
