### ISSUE TITLE
Consider integrating a template engine

### ISSUE THREAD

**Issue by luizmineo** [dart-lang/source_gen#39]
Writing code directly to a StringBuffer can be very tedious and error prone, so it would be nice if we could write templates for generated code.

For now, I'm using mustache templates to avoid the use of StringBuffer (I've rewritten the json serializable generator to test this out, and you can see the code [here](https://github.com/luizmineo/source_gen.dart/tree/master/lib/generators)). However, it's more a hack than a proper solution, since mustache was built for generating html files, not source code.

It'd be really cool if we had something like [StringTemplate](http://www.stringtemplate.org/) for Dart and source_gen.

**Comment by kevmoo** [comment]
Ooo...cool idea.

I'm likely not going to bake a template model into the core of `source_gen` – but I could see it used in something like `JsonGenerator`.

Long term, `JsonGenerator` will likely live in its own package. It's here now just as a non-trivial sample.

**Comment by jakemac53** [comment]
There isn't any reason to have this be directly integrated in source_gen imo, luckily we now have https://github.com/dart-lang/code_builder! It should be trivial to use that with source_gen.
