### ISSUE TITLE
Some problem with imports

### ISSUE THREAD

**Issue by MihaMarkic** [dart-lang/source_gen#399]
Is it possible that there is something wrong with allSupertypes I'm getting from imports?

I'm checking imported types like these
```dart
for (var i in library.element.library.imports) {
  for (t in i.importedLibrary.definingCompilationUnit.types) {
    for (var st in t.allSupertypes) {
      print("super: ${st.element.displayName}");
      }
  }
}
```

but I get only a single Object type as supertype even though types extends other types.

However, if I test it in a standalone app, like this:

```dart
ResolvedUnitResult result =await resolveFile("my.dart");
  CompilationUnit resolvedUnit = result.unit;
  CompilationUnitElement element = resolvedUnit.declaredElement;
```

I get supertypes correctly.

**Comment by natebosch** [comment]
Are you on the latest version of analyzer, `0.35.0`? There was a change in `build_resolvers` and the latest analyzer that could impact the behavior of some fields like `definingCompilationUnit`.

Have you tried going through `library.element.importedLibraries` instead of `library.element.library.imports`?

Can you provide a minimal repro?

**Comment by MihaMarkic** [comment]
[repro_supertypes.zip](https://github.com/dart-lang/source_gen/files/2854842/repro_supertypes.zip)

Attached is the sample. Once "flutter packages pub run build_runner build" runs, it should create tubular.immutable.dart part file.

Nevermind the code, look at comments. It should say
```dart
// Class is Tubular
// checking Subtype
// super: Object
// total derived types: 0
```

The weird part is that there is only one supertype found for the Supertype class and it is Object (third comment line). I would expect Tubular and _Tubular classes as well.
From lock files I see that it uses analyzer 0.34.2.

Perhaps I'm missing something obvious but I can't figure out what.

**Comment by MihaMarkic** [comment]
@natebosch Any news on this? Or any workaround to this - like can I get an absolute path to the .dart file from LibraryReader - so I can go with ResolvedUnitResult instead, at least for the time being.

**Comment by MihaMarkic** [comment]
@kevmoo It's also a (possible) bug, not just a question.

**Comment by kevmoo** [comment]
It'd be a bug in the analyzer package, not source_gen.

We want to help you either way, but this issue is not specific to this package.

**Comment by MihaMarkic** [comment]
@kevmoo Thanks for the info, is there an issue filed for it or should I?

**Comment by kevmoo** [comment]
I'd file one - https://github.com/dart-lang/sdk/issues/new

**Comment by MihaMarkic** [comment]
@kevmoo One last question - if I do it directly using analyzer, it works - see my top post. Is source_gen using it differently?

**Comment by kevmoo** [comment]
> @kevmoo One last question - if I do it directly using analyzer, it works - see my top post. Is source_gen using it differently?

You mean directly using the analyzer API (package:analyzer)? Are you using the same version of the package?

We're in a really weird spot here where there are two runtime models in the analyzer now: the "task model" and the "driver model".

pkg:build (and things built with it) are now migrated to the driver model. If you're using the API, there's a good chance you're still on the task model, which is going away.

You may have found a bug here. I'd file an issue and highlight this difference.

**Comment by MihaMarkic** [comment]
I think I know why I wasn't getting proper superclass types.
It was a problem because the class I was analyzing relies on a generated base class. Builder is deleting those on start of build process and thus analyzer can't find the base class declaration and just says 'Object'.
Basically I had this situation:

```
class _Root
class Root extends _Root // autogenerated by builder
class Problem extends Root // for this class I was getting the only supertype Object, not Root, _Root and Object.
```
