### ISSUE TITLE
Extract json_serializable test utils into an independant package

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/source_gen#403]
An unusual request for once:

I've been exploring a bit into the test folder of json_serializable and I got quite surprised to find a small testing framework included.

I think it would be interesting to extract everything related to `ShouldThrow`/`ShouldGenerate` into a reusable package.

**Comment by kevmoo** [comment]
@rrousselGit – take a look at the PR that's open. I'm pretty happy w/ where things ended up!

**Comment by kevmoo** [comment]
I'm going to run with this here https://github.com/kevmoo/source_gen_test

**Comment by kevmoo** [comment]
Here you go @rrousselGit - https://pub.dartlang.org/packages/source_gen_test
