### ISSUE TITLE
How can I get initializer value?

### ISSUE THREAD

**Issue by m1-nann** [dart-lang/source_gen#410]
I would like to get the initializer in the field corrected_time in code below. I found the `field.initializer`, but couldn't get much further. (the @Init annotation is temporary solution for now):
```dart
mixin PrerenderDoc on Doc implements AllowDelete {
  @Init(init_int: 0)
  int corrected_time = 0;
}
```

**Comment by kevmoo** [comment]
This is a question for `pkg:analyzer`. Please ask on https://stackoverflow.com/questions/tagged/dart

**Comment by shtse8** [comment]
I have the same question, but cannot search for the solution. @m1-nann Did you find it?
