### ISSUE TITLE
dart:ui.Color Type being discovered as dynamic

### ISSUE THREAD

**Issue by pavanpodila** [dart-lang/source_gen#421]
The `mobx_codegen` package is running into an issue (https://github.com/mobxjs/mobx.dart/issues/165) where the underlying builder gets the type for `dart:ui.Color` as `dynamic`.

**Versions**

1. source_gen **0.9.4+2**
1. build **1.1.3**
1. build_runner **1.3.1**

During debugging, we saw that the visitor sends the `FieldElement` with the wrongly discovered type of `dynamic`.

**Comment by natebosch** [comment]
This is happening because when we set up the `Resolver` we use the Dart SDK, not the Flutter SDK...

https://github.com/dart-lang/build/issues/733

**Comment by pavanpodila** [comment]
After lot of research yesterday :-) I learnt this the hard way! Hope the SDK becomes tool dependent and not baked in as it is today.
