### ISSUE TITLE
Builder not working for class field

### ISSUE THREAD

**Issue by lukasgarcya** [dart-lang/source_gen#441]
I have the class annotation bellow:
```
@Entity
class Todo {
String title;
@ManyToMany('title')
List<Todo> nextAction;
}
```

The builder for annotation ManyToMany not create file generate.

**Comment by jakemac53** [comment]
A `GeneratorForAnnotation` only looks at annotations on classes (or maybe other top level declarations), if you want to access the annotations on fields you need to crawl to those from the class (you can use a visitor or manually walk the class declarations, either way). See the analyzer apis for how that is done.
