### ISSUE TITLE
add ability to tell the source_gen that generated code may produce a code that needs code generation

### ISSUE THREAD

**Issue by sahandevs** [dart-lang/source_gen#442]
problem is described here : https://stackoverflow.com/questions/59503994/how-to-run-a-code-generator-on-the-top-of-another-code-generator

my suggestion is to add a method to the generator class like `doesGeneratesAnnotatedCode(String generatedSourceCode)` and using this method, rerun the generators over the generated code (instead of project)

**Comment by jakemac53** [comment]
It sounds like what you want is the `runs_before` option, https://pub.dev/packages/build_config#adjusting-builder-ordering.

That allows you to say a builder should always run before some other builder (usually because it generates code which requires some other builder).

**Comment by jakemac53** [comment]
I am going to close this for now but we can re-open if that doesn't solve your  use case

**Comment by sahandevs** [comment]
@jakemac53 
`runs_before` works great when you know what other builders should run. in this case you don't

for example

```

const int kApplicationType = 1;

@generateCode(kApplicationType == 1 ? """

@JsonSerializable()
class GeneratedClass {
  final String Name;
  final int id;
}

""" : """

@JsonSerializable()
class GeneratedClass {
  final String Name;
  final String id;
}

""")
abstract class Result with $GeneratedClass {}
```

Note: example above is just for demonstration and we can solve above problem with other methods too.

**Comment by jakemac53** [comment]
In the example above it looks like you have user configuration which would need to determine builder order. This isn't something we can really support because builder order needs to be static (defined ahead of time) and globally consistent.
