### ISSUE TITLE
Can two code-gen libraries coexist on the same dart file?

### ISSUE THREAD

**Issue by realcr** [dart-lang/source_gen#444]
Assuming that I have two different dart packages that perform code generation on the same file `my_file.dart`, what should I expect to have in `my_file.g.dart`? Will it contain code generation combined from both packages?

If what I suggested is not expected to work, is there an alternative way to have multiple dart packages perform code generation on the same file?

Thank you for your help!

**Comment by jakemac53** [comment]
This does work if you use the [SharedPartBuilder](https://pub.dev/documentation/source_gen/latest/source_gen/SharedPartBuilder-class.html)

**Comment by realcr** [comment]
Thanks, what a great time to live!
