### ISSUE TITLE
How to get the documentationComment of an *Annotation*?

### ISSUE THREAD

**Issue by xsahil03x** [dart-lang/source_gen#456]
```dart
@superEnum
enum _Attribute {
  @Data(fields: [DataField<int>('value')]) 
  /// Test Docs
  Intelligence,

  /// Test Docs
  @Data(fields: [DataField<int>('value')])
  Strength,
}
```

Getting the `documentationComment` from the `Intelligence` FieldElement works properly. 

But I am unable to find a way to get the comment for `Strength` FieldElement, this makes sense as the comment is on the `annotation` instead of the `FieldElement` in that case but I need I way to access that comment somehow. 
The users will be more comfortable with adding comments like the second option.

**Comment by natebosch** [comment]
Indeed the second option is what we recommend https://dart.dev/guides/language/effective-dart/documentation#do-put-doc-comments-before-metadata-annotations

I'm surprised this wouldn't work, I would expect the doc comment to still be associated with `Strength` even though there is an annotation in between... @scheglov do you know if this is expected?

**Comment by scheglov** [comment]
This is a bug in analyzer.
It was fixed in the bleeding edge.
https://github.com/dart-lang/sdk/issues/40865

**Comment by xsahil03x** [comment]
Thanks @scheglov and @natebosch :+1:
