### ISSUE TITLE
JsonSerializable: add option to omit null fields in toJson

### ISSUE THREAD

**Issue by kcprabase** [dart-lang/source_gen#458]
When serializing objects using toJson(), sometimes it is necessary that we do not include those items whose value are null. 

For eg. Lets say an integer property,  int PersonId  is null, it is then serialized as "{'personId': null, ... rest of properties}" . When I pass this to an asp.net controller in a JsonBody, it gives me error saying cannot pass null to int. but if nothing is passed for personId, asp.net will take default 0 for integer.

Default Value annotation set to 0 can help me here, but there are other cases where ignoring null values in toJson() method is very useful.

**Comment by kevmoo** [comment]
See https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/includeIfNull.html

**Comment by kcprabase** [comment]
Perfect.
Thanks.
