### ISSUE TITLE
Question: How to cast annotation.peek()?.objectValue

### ISSUE THREAD

**Issue by nguyenxndaidev** [dart-lang/source_gen#459]
I would like to have an annotation with property as an object:
```
@MyAnno(settings = Settings(a: 'a', b: 'b'))
class Todo {}
```

Now I want to get the annotation information:
```
// annotation is ConstantReader of @MyAnno
// print the value correctly
print(annotation.peek('settings')?.objectValue); // Settings(a = String (a), b = String (b))

// Cannot cast to Settings
// Error: type 'DartObjectImpl' is not a subtype of type 'Settings' in type cast
final settings = annotation.peek('settings')?.objectValue as Settings;
```

How could I get the `Settings` object?

I know there are workarounds, such as using something else like Map. But I really want to use nested objects similar to Java.

Best regards

**Comment by nguyenxndaidev** [comment]
I found a way to get the value: `annotation.peek('settings')?.peek('a')?.stringValue`

But it would be nicer if I can get the `Settings` object directly. Any idea?

**Comment by natebosch** [comment]
`ConstantReader` exists _because_ it's not easy to get a real instance during codegen. If we could easily give you an instance of `Settings` we would have skipped `ConstantReader` altogether and given you an instance of `MyAnno` from the start.

`annotation.read('settings').read('a').stringValue` is the recommended approach if you know those fields will exist, and `annotation.peek('settings')?.peek('a')?.stringValue` is the recommended approach if those fields might not exist.
