### ISSUE TITLE
To many parts make the build hang

### ISSUE THREAD

**Issue by a14n** [dart-lang/source_gen#46]
With _1.9.0.dev_10_13_ and _source_gen-0.2.4_ I face an issue when there are too many parts in a lib. The generator never ends.

I don't know if this is an analyzer issue but _0.24.0_ doesn't fix this issue.

Here is a example to reproduce.

pubspec.yaml :

``` yaml
name: source_gen_issue
version: 0.0.1
dependencies:
  source_gen: any
```

Generate parts and lib by running _genlib.dart_ :

``` dart
import 'dart:io';

main() {
  var libContent = '''
library source_gen_issue;

import 'package:source_gen/generators/json_serializable.dart';

part 'my.g.dart';

''';
  for (var i = 1; i <= 80; i++) {
    var n = i.toString().padLeft(3, '0');
    libContent += "part 'part${n}.dart';\n";
    new File('lib/part${n}.dart').writeAsStringSync('''
part of source_gen_issue;

@JsonSerializable()
class Person${n} extends Object with _\$Person${n}SerializerMixin {
  final String firstName, middleName, lastName;
  final DateTime dateOfBirth;

  Person${n}(this.firstName, this.lastName, {this.middleName, this.dateOfBirth});

  factory Person${n}.fromJson(json) => _\$Person${n}FromJson(json);
}
''');
  }
  new File('lib/my.dart').writeAsStringSync(libContent);
}

```

build.dart :

``` dart
import 'package:source_gen/generators/json_serializable_generator.dart' as json;
import 'package:source_gen/source_gen.dart';

void main(List<String> args) {
  build(args, const [const json.JsonSerializableGenerator(),],
      librarySearchPaths: ['lib']).then((msg) {
    print(msg);
  });
}
```

Either by running _build.dart_ or with a change in one of the file the build.dart never ends. In my example the limit is between 70 and 80 parts.

**Comment by kevmoo** [comment]
I find that 64 works and 65 hangs.

Could you test those out for me quick?

Curious if it's a memory thing...or what

**Comment by kevmoo** [comment]
I find that 64 works and 65 hangs.

Could you test those out for me quick?

Curious if it's a memory thing...or what

**Comment by a14n** [comment]
Here : 75 works, 76 hangs
WIth `Dart VM version: 1.9.1 (Tue Mar 24 23:04:09 2015) on "linux_x64"`

**Comment by kevmoo** [comment]
I think we found a bug in the analysis API. Good job!

:smile: 

I'll work on a minimal repo and get something filed for them.

**Comment by kevmoo** [comment]
See https://code.google.com/p/dart/issues/detail?id=23017

**Comment by a14n** [comment]
Regarding `AnalysisContextImpl.DEFAULT_CACHE_SIZE = 64;` it's strange that I went up to 75.

**Comment by kevmoo** [comment]
@a14n Did you try hacking the const value in pub cache to see if it fixes it?

**Comment by a14n** [comment]
No. Did you try it ?

**Comment by kevmoo** [comment]
Leaving this issue open, but the patch is committed (with tweaks). Thanks!

**Comment by jakemac53** [comment]
closing as I assume this is resolved
