### ISSUE TITLE
How I can get element source code. 

### ISSUE THREAD

**Issue by AlexVegner** [dart-lang/source_gen#461]
I would like to have ability to copy methods with body to generated code. 

#### Example class:
```dart
class User {
   String hello() {
      return "Hello";
   }
}
```

#### Usage code
```dart
final classElement = element as ClassElement;
final List<String> methodList =
        classElement.methods.map<String>((MethodElement method) {
      return method.source.toString()
    }).toList();

final methodsString = methodList.join('\n');
```

#### Expected: 
methodsString =
```dart
String hello() {
      return "Hello";
   }
```

#### Actual:
methodsString = 
```dart
String hello()
```

**Comment by bgpinto** [comment]
I would like to know it as well!

**Comment by tolotrasamuel** [comment]
Look for buildStep.resolver(element).toSource()

**Comment by jakemac53** [comment]
https://pub.dev/documentation/build/latest/build/Resolver/astNodeFor.html is the api you are looking for, you need to get the AST node for an element in order to see the full source (including the body).

**Comment by tolotrasamuel** [comment]
@jakemac53  how to do the opposite?
Getting Element from AstNode?

**Comment by jakemac53** [comment]
> Getting Element from AstNode?

I don't believe you can, or at least not directly.

**Comment by tolotrasamuel** [comment]
My goal is to find the declaration of a MethodInvocation
For example, foo(), can you give a hint on which API to use to know that foo is declared in a file "foo.dart"
