### ISSUE TITLE
Question: ignore_for_file in LibraryBuilder

### ISSUE THREAD

**Issue by edwardaux** [dart-lang/source_gen#464]
Apologies if this has been asked and answered before... one of my dependencies (https://github.com/Milad-Akarie/auto_route_library/blob/master/auto_route_generator/lib/builder.dart) is using `LibraryBuilder` to generate its output and I've noticed that it doesn't honour the `ignore_for_file` directive in my `build.yaml`

Poking around in the source_gen source, I can see that `ignore_for_file` only appears to be implemented for `CombiningBuilder`.

Just curious if there's something I can use (or encourage the author of my dependency to use) to achieve the same result?  Thanks

**Comment by kevmoo** [comment]
https://pub.dev/documentation/source_gen/latest/source_gen/LibraryBuilder-class.html has a `header` param that can be used to populate such things. I'd make a request there!
