### ISSUE TITLE
How to access the value of a constant custom object?

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/source_gen#465]
Let's consider the following context:

I have a constant class that has some value:
```dart
class Wrapper {
    final String value;

    const Wrapper(this.value);
}
```

On annotation:
```dart
class MyAnnotation {
    Wrapper value;
}
```

Finally, using the annotation on a class:
```dart
@MyAnnotation(const Wrapper('My nice value'))
class MyClass { }
```
---

How can my generator access the passed value? If I were simply using `String` I could use, for instance, `stringValue`. If I use `literalValue`, that has a assignature of `Object`, it will throw an error, as it's actually not considered an literal. However, it is a `const` value, and thus, should be accessible to the builder.

So, remains the question... How can I access the constant passed object?

**Comment by simphotonics** [comment]
You could use the following:

```Dart
/// Let [myAnnotationCR] be an instance of [ConstantReader] representing your annotation:

/// Retrieve the field with name 'value' from [MyAnnotation]:
final ConstantReader wrapperCR = myAnnotation.peek('value');

/// Retrieve the field with name 'value' from [Wrapper].
final String value = wrapperCR.peek('value')?.stringValue;
```

Btw, I just published a library called generic_reader that might be useful when retrieving more complex constants (for example with parameterized type). You might want to have a look on pub.dev.

Just a suggestion, to make your code easier to read I would rename one of 'value' fields.

**Comment by kevmoo** [comment]
A general solution here is **hard** – we had it for a while and got rid of it to avoid complexity.

Perhaps the suggestion from @simphotonics is a place to start.

**Comment by mateusfccp** [comment]
I ended up making use of enums and mapping it to behavior. However, this came with the compromise of getting rid of extensibility for my package.
