### ISSUE TITLE
Detect if file is a entrypoint

### ISSUE THREAD

**Issue by bohdanbirdie** [dart-lang/source_gen#467]
Is it possible to detect if the `Library` inside of `LibraryBuilder` is actually the entrypoint file with `main` method?

**Comment by jakemac53** [comment]
You can check manually for a method named `main` in the `LibraryElement.topLevelElements`, but that doesn't guarantee it is _the_ entrypoint just _one potential entrypoint_.

Entrypoints may be wrapped in additional entrypoints by builders to set up some default logic (the test package does this for all tests for instance).
