### ISSUE TITLE
Can source_gen be used for other types of file inputs?

### ISSUE THREAD

**Issue by Grohden** [dart-lang/source_gen#479]
I'm trying to find a way to use `source_gen` to be able to make [my package](https://github.com/Grohden/icomoon-selection-gen) generate dart code by reading a json, but I couldn't find a way to generate code reading other file types using `source_gen`

I see that is stated in the readme:
> A framework for writing Builders that **consume** and produce Dart code.

I know I don't need `source_gen` to generate that code, my package already works without it, but I'm insisting in trying `source_gen` for the `ignore_for_file` option.

I feel like the `ignore_for_file` is a standard thing that all codegen libs should/could be using, but it seems that it is limited to packages that use `source_gen` AND consume only dart code...

Perhaps a more real use case is the artemis package, their current solution was to add the option as a 'internal' option
so if I'm understanding [this solution](https://github.com/comigor/artemis/pull/210) correctly, a user would have do duplicate the `ignore_for_file` option (one for json gen, and one for the artemis gen), is this the approach I should be taking or am I missing something in the docs?

**Comment by jakemac53** [comment]
The `source_gen` package is only built for consuming Dart code inputs and it doesn't work for other types of inputs.

Any builder should be able to output `// ignore_for_file: <code>` at the top of the dart files they produce, which could be user configurable or hard coded.

**Comment by Grohden** [comment]
@jakemac53 thank you for the response.

So.. ok, would be nice to reuse the `source_gen|combining_builder` ignore options to not duplicate all those ignore rules, but that would be just a convenience..
In any case, thanks again for the response, I'm closing this since my question was answered

**Comment by natebosch** [comment]
I think you could use `source_gen:combining_builder` still. As long as your builder is outputting `.g.part` files you can configure the `runs_before` and `applies_builder` config for it even without using the `SharedPartBuilder` API.
