### ISSUE TITLE
Avoid resolving all inputs when possible

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/source_gen#481]
Version `1.5.0` of the `build` package adds a new api - `compilationUnitFor` - which could be used in order to cheaply skip some libraries that for instance have no annotated elements at all.

The `LibraryReader` would likely need to become lazy - taking only a `BuildStep` + `assetId` and not a `LibraryElement`. In general that could be a good change though.

This has the potential to very dramatically improve the speed of all source_gen builders, which usually today end up fully resolving every single library in any package they are applied to.

**Comment by natebosch** [comment]
How many builders do we think currently don't use the `LibraryReader`?

**Comment by jakemac53** [comment]
This optimization would be pretty specifically targeted at `GeneratorForAnnotation` generators. The goal would be to efficiently skip the vast majority of inputs (at a minimum, those without any top level annotated elements at all which should be most).

I assume once you find a real annotation that you care about most builders would use the `LibraryReader`.
