### ISSUE TITLE
Import prefixes removed on code generation.

### ISSUE THREAD

**Issue by MatthewCoetzee412** [dart-lang/source_gen#483]
Hi 👋 ,

I am using the Freezed library which uses source-gen and when the code is generated the Import prefixes I am using are removed. Is their a way to prevent this or is their a way to fix it?

Thanks,
- Matt

**Comment by jakemac53** [comment]
I am not sure what exactly behavior you are describing here - source_gen does not alter your source files in any way.

It is possible that `freezed` is doing that... although they shouldn't be. You might want to file an issue on that repo?

**Comment by natebosch** [comment]
Can you clarify which imports these are?

As far as I can tell `freezed` only generates a part file which wouldn't have imports:

https://github.com/rrousselGit/freezed/blob/74864f355ed97ce3ad89def25467ef23f4b66f86/packages/freezed/lib/builder.dart#L8

They don't have any imports to `dart:io`or package that would overwrite a file directly. And `build_runner` will never write to a source file.

What is the exact command you run when you see an import prefix get removed?

**Comment by MatthewCoetzee412** [comment]
I have for example:

```Dart
import '.../food.dart' as food;
import '.../some_other_package.dart;
```

I run "flutter packages pub run build_runner watch".

But Freezed seems to remove the "food" prefix in the generated file, meaning I have to manually add those prefixes in the .freezed.dart generated file each time Freezed generates a new file. I think the title was somewhat misleading and sorry about that. Should I open an issue on the freezed package?

**Comment by natebosch** [comment]
Ah, so it's not the `import` directives that are change, but rather the generated code will have a reference to `foo` when it should be `food.foo` because you have an import prefix.

yes, that issue should be filed against the `freezed` package. I'll close this one for now since I don't think there is any actions for this repo.
