### ISSUE TITLE
Support `allowSyntaxErrors` flag

### ISSUE THREAD

**Issue by fertrig** [dart-lang/source_gen#485]
[This PR](https://github.com/dart-lang/build/pull/2797), from the `build` package, added code that throws when resolving libraries with syntax errors. It also added the flag `allowSyntaxErrors` to `BuildStep.resolver.libraryFor()` to opt-out of that behavior.

However, when using source_gen, I cannot find a way to opt-out of that behavior.

The method `_Builder.build()` in builder.dart in the source_gen package is using `buildStep.inputLibrary` which throws when resolving a library with syntax errors.

The source_gen `*Builder` classes could be modified to accept a flag to allow syntax errors. Their constructors could take a named parameter for the flag which could then be used inside the `_Builder.build()` method to call `buildStep.resolver.libraryFor(...)` instead of `buildStep.inputLibrary`.

I could work on a PR for that change if the approach makes sense.

**Comment by jakemac53** [comment]
That makes sense to me, although I am concerned this won't fully resolve the issue... the reason being that most source gen builders probably don't want to enable this, and if the user has any source_gen builder that doesn't allow syntax errors they will end up with errors in their build.

I am curious what your use case is for allowing syntax errors?

**Comment by fertrig** [comment]
I agree with your concern, if the user has multiple source_gen builders, then it mail fail anyways. However, we have already implemented an experience where syntax errors are reported after our source_gen builders have run.

Supporting the `allowSyntaxErrors` flag in source_gen will be a stop gap until we can change the experience to report syntax errors before source_gen runs.

It's not that our use case allows for syntax errors, the issue is that our experience already relied on the builders not throwing when there were syntax errors.

**Comment by jakemac53** [comment]
Ah ok, ya that is one of the use cases for which we added this option to disable this in the first place (custom error reporting). So it sounds fairly reasonable to just add this option to the source_gen package to allow custom error reporting in source_gen builders.

cc @kevmoo any concerns?

**Comment by kevmoo** [comment]
An opt-in flag? No big concerns.

**Comment by jakemac53** [comment]
@fertrig if you want to put together a PR for this it sounds like something we would accept then 👍
