### ISSUE TITLE
Add support for nullsafety

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/source_gen#493]
I am upgrading my package (Kiwi) https://github.com/vanlooverenkoen/kiwi/issues/51

But it seems that source_gen is not yet migrated to support nullsafety. Is there a timeline on when this could be added?

**Comment by jakemac53** [comment]
This will be blocked on package:build, which is blocked on package:analyzer

**Comment by vanlooverenkoen** [comment]
Blocked because of: https://github.com/dart-lang/build/issues/2920

**Comment by kevmoo** [comment]
I believe this has been fixed!

**Comment by kevmoo** [comment]
@vanlooverenkoen – do you want (1) the code in source_gen to be null safe? Or (2) just to support generating null-safe code?

We have (2) done, not (1).

**Comment by vanlooverenkoen** [comment]
I want the code in code_gen to be nullsafe

**Comment by kevmoo** [comment]
We need to get all of the downstream packages migrated, first.

You can still USE source_gen to generate null-safe code.

`json_serializable` does this now!

**Comment by simolus3** [comment]
After 2.0 of `build` is released, we'd still be blocked by `dart_style` (and `build_verify` not supporting build 2.x, but that's not relevant now). 

Apart from that, I'm happy to migrate this package as well if no-one is working on it yet.
