### ISSUE TITLE
part

### ISSUE THREAD

**Issue by vsevolod19860507** [dart-lang/source_gen#496]
0.9.10 does not work if the file is part of another. Try to generate code from multiple files into one, using "part"

Maybe I configured something wrong, but it worked before and now works if I roll back to the version 0.9.9

**Comment by natebosch** [comment]
Closing since I don't think this issue is actionable. With the current release of `source_gen` this pattern is implemented with `PartBuilder` or `SharedPartBuilder`. If the docs on those types are insufficient to resolve the issue we can expand them.
