### ISSUE TITLE
Ability to call a function passed via Annotation within generateForAnnotatedElement

### ISSUE THREAD

**Issue by KieranLafferty** [dart-lang/source_gen#501]
Hey there! 

I'm trying to build an annotated part builder that allows a static function to passed input data in and an output function to process the input data and return a `Spec` type which will in turn be codegened into the file. 

The purpose of this is I find myself wasting a lot time doing boiler plate stuff to accomplish the same goal of taking in data and generating models and wanted a more abstract/flexible way to generate code

Here's an example of what the class annotation would look like 

```
class FakeJsonInput implements FlexPluginInputInterface<Map<String, dynamic>> {
  const FakeJsonInput();

  @override
  Future<Map<String, dynamic>> Function() get builder => () => Future.value({
        'name': 'Kieran',
      });
}

@FlexGenerator(
  plugin: FlexPluginMap(
    input: FakeJsonInput(),
    output: FlexPluginMapOutput(),
  ),
)
class TestClass {}
```

The goal here isn't to build a single generator, it's to build an extensible codegen that I can reuse for various things where I need to generate based on data known at compile time

**Input Interface**
```
typedef FlexPluginInputBuilder<T> = FutureOr<T> Function();

abstract class FlexPluginInputInterface<T> {
  final FlexPluginInputBuilder<T> builder;

  const FlexPluginInputInterface(this.builder);
}
```

**Output interface**
```
typedef FlexPluginOutputBuilder<T> = FutureOr<Spec> Function(T object);

abstract class FlexPluginOutputInterface<T> {
  final FlexPluginOutputBuilder<T> builder;

  const FlexPluginOutputInterface(this.builder);
}
```

Sorry for the excessive info just want to provide context to help guide any answers anyone may have. 

So where I'm stuck is that I can receive the `FlexGenerator` annotation inside of the `generateForAnnotatedElement` as follows (it's not working currently, but pasting for context)

```
class FlexAnnotatedBuilder extends GeneratorForAnnotation<FlexGenerator> {
  const FlexAnnotatedBuilder();

  @override
  Stream<String> generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async* {
    final plugin = annotation.read('plugin');
    final input = plugin.read('input').read('builder').literalValue;
    final output = plugin.read('output').read('builder').literalValue;

    final emitter = DartEmitter();
    final codeFormatter = DartFormatter();

    final codeSpec = await flexGenerate(
      input: input,
      output: output,
    );
    final dartCode = codeSpec.accept(emitter);

    yield codeFormatter.format('$dartCode');
  }
}
```

Essentially I'm wondering if it's possible to get a reference to the actual input/output function instances so that I can call them inside the code generator itself and get the functions return instance out of the functions

I can get the AST tree of the input/output functions via `objectValue` but when I calling `literalValue` as is shown above I get "is not a literal" on them. Any guidance or is this even possible?

**Comment by jakemac53** [comment]
You would have enough information to generate an invocation of the function in code, but you can't directly invoke it yourself in your code generator. The analyzer can only do constant evaluation, it cannot invoke function objects from code it is analyzing.

Does that answer your question?

**Comment by KieranLafferty** [comment]
Yea that answers the question.

It's a big hack but I was considering doing something where I pipe the implementation source code of the `FutureOr<T> Function()` to a string then pipe that string  into the following to execute it and get the desired instances out of to be used in the codegen runtime


```
   final inputCodeAsString = <generate string representation of plugin handler>
   final uri = Uri.dataFromString(
      '''
    import "dart:isolate";

    void main(_, SendPort port) async {
      port.send($inputCodeAsString);
    }
    ''',
      mimeType: 'application/dart',
    );
    final port = ReceivePort();
    await Isolate.spawnUri(uri, [], port.sendPort);
```
Apart from it being really dangerous to execute arbitrary code like this, do you foresee any major issues with this approach?

Thanks so much for your answer :) Undoubtedly saved me a bunch of time going down the path of trying to execute directly from the ast tree

**Comment by jakemac53** [comment]
Isolates are pretty heavy weight today, would be my main concern. There is some work on lighter weight isolates happening but i don't know the details.

Ideally there would be a single longer lived isolate or something which you could consistently send requests to and get responses back, but I am not sure that would really work for what you are trying to do here. Possibly you could create one for each unique annotation you see (or maybe more specifically one per input/output combo?).

You can share resources across builders using the [Resource class](https://pub.dev/documentation/build/latest/build/Resource-class.html) and [fetchResource](https://pub.dev/documentation/build/latest/build/BuildStep/fetchResource.html) method to get shared instances.

**Comment by KieranLafferty** [comment]
Awesome will check it out really appreciate the feedback on this. Feel free to close this issue out as my question has been answered :)
