### ISSUE TITLE
Build order of two generated files

### ISSUE THREAD

**Issue by atreeon** [dart-lang/source_gen#510]
I have two code generators, `MockCreator` & `ValueT2`.

`ValueT2` creates a new class from a more simple class.  `MockCreator` consumes, in its output, the new class.  Unfortunately my `MockCreator` generated file has the dynamic type instead of the newly created class type.

I think this is to do with the order my files are created.  I tried to provide some hints to the build order.  In my `MockCreator` `build.yaml` I have put the line
```    required_inputs: [".valuet2.dart"]```

& in my `value_t2` `build.yaml` I've added the line
```    runs_before: ["mock_creator_generator"]```

In my `build.dart` file (.dart_tool) it shows the list of builders with mock_creator_generator higher up the list compared to value_t2_generator

Any ideas as to why this is the case?  Would you need an example?

I include my build.dart output here

```
final _builders = <_i1.BuilderApplication>[
  _i1.apply(r'copy_with_e_generator:copy_with_e', [_i2.copyWithEBuilder],
      _i1.toDependentsOf(r'copy_with_e_generator'),
      hideOutput: true,
      appliesBuilders: const [r'source_gen:combining_builder']),
  _i1.apply(r'mock_creator_generator:mock_creator', [_i3.mockCreatorBuilder],
      _i1.toDependentsOf(r'mock_creator_generator'),
      hideOutput: false,
      appliesBuilders: const [r'source_gen:combining_builder']),
  _i1.apply(r'source_gen:combining_builder', [_i4.combiningBuilder],
      _i1.toNoneByDefault(),
      hideOutput: false, appliesBuilders: const [r'source_gen:part_cleanup']),
  _i1.apply(r'value_t2_generator:value_t2', [_i5.valueT2Builder],
      _i1.toDependentsOf(r'value_t2_generator'),
      hideOutput: false),
  _i1.applyPostProcess(r'source_gen:part_cleanup', _i4.partCleanup)
];
```

**Comment by jakemac53** [comment]
> runs_before: ["mock_creator_generator"]

This needs to be the full builder ID not just the package name (that would default it to `mock_creator_generator:mock_creator_generator`). It looks like the actual builder name is `mock_creator_generator:mock_creator` so you should have:

`runs_before: ["mock_creator_generator:mock_creator"]`

**Comment by atreeon** [comment]
thank you @jakemac53, the order in build.dart is correct now but I still have dynamic.  I'll take another look in the morning

**Comment by jakemac53** [comment]
If you are using `SharedPartBuilder` you will have to migrate the first builder to a `PartBuilder` - with its own extension and `part` imports in the user code. Otherwise the shared part file is not emitted until after the `source_gen:combining_builder` runs

**Comment by atreeon** [comment]
thanks for your help @jakemac53.  I must have looked at this with slightly tired eyes last night, the order hadn't changed so mock_creator was still being built before valuet2.  However, I updated `build`, `analyzer` and `source_gen` so they are all on the latest version and it worked just fine after getting the partid name right (was already using PartBuilder).  Thank you!
