### ISSUE TITLE
Get AST of annotation

### ISSUE THREAD

**Issue by Nolence** [dart-lang/source_gen#527]
Hi !  I've been using the workaround described [here](https://github.com/dart-lang/language/issues/1297#issuecomment-724096226) to type my annotation but now I'm having trouble trying to get the ast of my annotation. For example say I have the user define the root of a firebase collection

```dart
part 'root.fire.dart';

// UndefinedType is not created until I generate output in my `root.fire.dart` file
const _UsersCollection = Collection<UndefinedType>(name: 'users');

@root
class Database with _$Database {
  // TODO: This should have the option to pass in an app
  @_UsersCollection
  Database._();

  static final instance = Database._();
}
```

I can get annotations over the named constructor `_` but how do I then get the **non-synthetic** element declaration `const _UsersCollection`.

I tried this but because I always get back a synthetic element from `declaration` calling `getElementDeclaration` by design returns null

```dart
@override
FutureOr<String> generateForAnnotatedElement(
  Element element,
  ConstantReader annotation,
  BuildStep buildStep,
) async {
  if (element is! ClassElement) {
    // ...
  }

  final stringBuffer = StringBuffer();
  final constructor = element.constructors.singleWhere(
    (constructor) => constructor.displayName == '_',
    orElse: () {
      // ...
    },
  );

  for (final annotation in constructor.metadata) {
    final annotationElement = annotation.element!.declaration!;

    final elementDecleration = element.library.session
        .getParsedLibraryByElement(element.library)
        .getElementDeclaration(annotationElement);

    // elementDecleration is null i think because annotationElement is synthetic

    final node = element.node; // throws

    final String type = _getUndefinedType(node);

    _createClassWithName(type);
  }
}
```

I want to get the ast because I need to get the undefined type on `Collection<T>` so I can use that name to build it. Any help is much appreciated.

**Comment by natebosch** [comment]
@scheglov, @devoncarew  - Do we have a support path for questions on using the Analyzer APIs like this?

**Comment by devoncarew** [comment]
The best place to ask is likely the analyzer-discuss list, referenced from here: https://dart.dev/community.

**Comment by natebosch** [comment]
In this case I think the following will get you close

```dart
final annotationElement = annotation.element;
// note, the following may not work if the code has a different pattern
// for example if the annotation isn't a top level variable...
final variable = (annotationElement as PropertyAccessorElement).variable;
final astNode = await buildStep.resolver.astNodeFor(variable);
```
