### ISSUE TITLE
Option to generate an instance "updateFromJson" mixin method

### ISSUE THREAD

**Issue by skalkin** [dart-lang/source_gen#54]
Sometimes, instead of using the factory "fromJson" method that creates a new instance, it is preferable to be able to apply json for an existing object (use case: settings deserialization, when there are already listeners attached to the events of the existing settings instance). This option would be quite handy in such cases!

**Comment by kevmoo** [comment]
You mean something like `updateFromJson`?

**Comment by skalkin** [comment]
Yes, exactly.

**Comment by kevmoo** [comment]
@skalkin good idea, but I'm likely not going to get to it. This project was meant as a demo of the source generation concept – the json bits are just a nice demo.

If you want to jump in and have a go, I'd love to see a pull request.

Just wanted to set expectations.

**Comment by skalkin** [comment]
Thanks @kevmoo, there will be a pull request when I get to it :)

Also, are you interested in having generators for comparing and cloning objects as part of your library, too, or would you rather have them elsewhere?

**Comment by matanlurey** [comment]
Closing since this request is from 2 years ago.
