### ISSUE TITLE
JsonSerializableGenerator does not work with read-only properties

### ISSUE THREAD

**Issue by skalkin** [dart-lang/source_gen#55]
I think it would make more sense if generator simply ignores such properties.

```dart
@JsonSerializable()
class Test {
  int get bar => 0;
}
```

Output: `TODO: Make the following fields writable or add them to the constructor with matching names: bar`

**Comment by skalkin** [comment]
...same thing with the `static const` and `static final`.

**Comment by Andersmholmgren** [comment]
particularly annoying that it picks up

```
int get hashCode
```

as it means you can't use this for a lot of classes

**Comment by kevmoo** [comment]
Great point. Pull requests welcome!
