### ISSUE TITLE
Apply dart_style's non-whitespace style fixes, like `dart format . --fix`

### ISSUE THREAD

**Issue by bradyt** [dart-lang/source_gen#551]
I am wondering if source_gen can implement something so that libraries, especially built_value, produce code that `dart format . --fix` won't modify.

The rest is copied from original issue at https://github.com/google/built_value.dart/issues/1086.

> I have my `*.g.dart` files committed in git, and I have `dart format . --fix` running in CI. I would like it if the code generated by built_value followed the advice found in dart format's --fix rules.
> 
> ```
> > dart help format
> ...
>     --fix                      Apply all style fixes.
> ```
> 
> - https://github.com/dart-lang/dart_style#style-fixes
> - https://github.com/dart-lang/dart_style/blob/2.0.3/lib/src/style_fix.dart
> 
> 
> To see what this looks like, try a fresh clone of built_value and try `dart format . --fix` there.
> 
> For example,
> 
> ```diff
> modified   example/lib/values.g.dart
> @@ -6,16 +6,16 @@ part of values;
>  // BuiltValueGenerator
>  // **************************************************************************
>  
> -Serializer<SimpleValue> _$simpleValueSerializer = new _$SimpleValueSerializer();
> +Serializer<SimpleValue> _$simpleValueSerializer = _$SimpleValueSerializer();
> ```
> 
> I didn't attempt to dig deep into the issue, I don't know if a related issue can be filed with source_gen, for example.
> 
> I'll try the following as a quick fix:
> 
> ```
> dart format $(find . \( -name '*.dart' ! -name '*.g.dart' \)) --fix
> ```

**Comment by jakemac53** [comment]
Hmm we do run dart format generally on code (I think it allows you to override this also, but the default is to use dart format).

If there is an imperative api for applying fixes, I could see source_gen just doing that? At least by default.

**Comment by bradyt** [comment]
Never mind, deleting comment (and this one) and I'll probably reply at other thread.
