### ISSUE TITLE
Exception with json_serializable on String? override (FieldElementImpl)

### ISSUE THREAD

**Issue by chunghha** [dart-lang/source_gen#555]
https://github.com/rrousselGit/freezed/issues/507#issue-984354925

**Describe the bug**
Following build_runner command is throwing an exception so generation of 'risk_factor.model.g.dart' gets failed.

**dart run build_runner build --delete-conflicting-outputs --verbose**

> **InconsistentAnalysisException**: Requested result might be inconsistent with previously returned results
> 
> package:analyzer/src/dart/analysis/session.dart 197:7      AnalysisSessionImpl._checkConsistency
> package:analyzer/src/dart/analysis/session.dart 107:5      AnalysisSessionImpl.getParsedLibraryByElement
> package:source_gen/src/type_checker.dart 305:16            UnresolvedAnnotationException._findSpan
> package:source_gen/src/type_checker.dart 344:24            new UnresolvedAnnotationException._from
> package:source_gen/src/type_checker.dart 114:43            TypeChecker._computeConstantValue
> package:source_gen/src/type_checker.dart 139:21            TypeChecker._annotationsWhere
> dart:core                                                  Iterable.isEmpty
> package:source_gen/src/type_checker.dart 73:20             TypeChecker.firstAnnotationOf
> package:json_serializable/src/utils.dart 17:21             _jsonKeyAnnotation
> package:json_serializable/src/utils.dart 27:5              hasJsonKeyAnnotation
> dart:collection                                            ListMixin.firstWhere
> package:json_serializable/src/field_helpers.dart 30:16     new _FieldSet
> package:json_serializable/src/field_helpers.dart 102:19    createSortedFieldSet.<fn>
> dart:core                                                  Iterable.toList
> package:json_serializable/src/field_helpers.dart 103:8     createSortedFieldSet
> package:json_serializable/src/generator_helper.dart 54:26  GeneratorHelper.generate
> 
> [SEVERE] json_serializable:json_serializable on lib/src/clpapi/**risk_factor.model.dart**:
> 
> Could not resolve annotation for `String? type`.
> package:source_gen/src/type_checker.dart 114:7             TypeChecker._computeConstantValue
> package:source_gen/src/type_checker.dart 139:21            TypeChecker._annotationsWhere
> dart:core                                                  Iterable.isEmpty
> package:source_gen/src/type_checker.dart 73:20             TypeChecker.firstAnnotationOf
> package:json_serializable/src/utils.dart 17:21             _jsonKeyAnnotation
> package:json_serializable/src/utils.dart 27:5              hasJsonKeyAnnotation
> dart:collection                                            ListMixin.firstWhere
> package:json_serializable/src/field_helpers.dart 30:16     new _FieldSet
> package:json_serializable/src/field_helpers.dart 102:19    createSortedFieldSet.<fn>
> dart:core                                                  Iterable.toList
> package:json_serializable/src/field_helpers.dart 103:8     createSortedFieldSet
> package:json_serializable/src/generator_helper.dart 54:26  GeneratorHelper.generate

**To Reproduce**

This is the '**risk_factor.model.dart**' 
Strange thing is that I have **String? type,** in other model classes but only this particular class gets the exception on build.

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'risk_factor.model.freezed.dart';
part 'risk_factor.model.g.dart';

@freezed
class RiskFactorModel with _$RiskFactorModel {
  factory RiskFactorModel({
    String? type,
    String? value,
    String? override,
  }) = _RiskFactorModel;

  factory RiskFactorModel.fromJson(Map<String, Object?> json) =>
      _$RiskFactorModelFromJson(json);
}
```

Flutter version:
> [✓] Flutter (Channel master, 2.6.0-1.0.pre.142, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
>     • Flutter version 2.6.0-1.0.pre.142 at <snip>
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision cf806f7d5f (3 hours ago), 2021-08-31 11:11:04 -0700
>     • Engine revision fe89463f14
>     • Dart version 2.15.0 (build 2.15.0-66.0.dev)
> 

Package versions in the lock:

> analyzer: version: "2.1.0"
> build_runner: version: "2.1.1"
> source_gen: version: "1.1.0"
> 

**Expected behavior**
Just building of this particular class is fine as the other model classes with freezed.

**Comment by jakemac53** [comment]
There are two things happening here:

1. source_gen is failing to resolve some annotation in the file (it is a bit hard to confirm which one due to the next error).
2. the error reporting code is directly using the analyzer session to report the annotation location, which causes an `InconsistentAnalysisException`.

The first fix here should be to resolve the 2nd error, by using [astNodeFor](https://pub.dev/documentation/build/latest/build/Resolver/astNodeFor.html) instead of the session directly [here](https://github.com/dart-lang/source_gen/blob/master/source_gen/lib/src/type_checker.dart#L304).

Then hopefully that should help with diagnosing the 1st issue.

**Comment by chunghha** [comment]
Thanks, @jakemac53 
Is there anything I (as an enduser of this package) can try from my end to get more info for the two things you mentioned?

By "Could not resolve annotation for String? type." shown in the error report, I thought error is related to the property type but I have 15 model classes with "String? type" property in the folder like as AddressModel below. But, those are all build OK except the RiskFactorModel posted in error.

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'address.model.freezed.dart';
part 'address.model.g.dart';

@freezed
class AddressModel with _$AddressModel {
  factory AddressModel({
    String? type,
    String? address1,
    String? address2,
    String? city,
    String? state,
    String? zipcode,
    String? country,
    String? county,
  }) = _AddressModel;

  factory AddressModel.fromJson(Map<String, Object?> json) =>
      _$AddressModelFromJson(json);
}
```

**Comment by jakemac53** [comment]
I think this is coming from an _annotation_ on a generated field on the `_$AddressModel` class (or some related class generated into one of the other part files).

You could try opening up the `.freezed.dart` file and see what that looks like.

**Comment by jakemac53** [comment]
Ok so I looked into this a bit but its actually going to require a breaking change to fix I think. The problem is the type checker doesn't require you to pass a `Resolver` today, which it would need in order to use the `astNodeFor` api.

That would be a breaking change (and a pretty annoying one at that probably). I am not sure what approach we want to take here. The only thing I can think of right now would be to just handle this error and fail more gracefully :/.

**Comment by jakemac53** [comment]
Another (possibly less annoying) option would be to have `annotationsOf` and `annotationsOfExact` require a resolver to be passed in, if `throwOnUnresolved` is `true`.

**Comment by chunghha** [comment]
As I commented out the override property in the RiskFactorModel, the build gets fine. So now I think that "String? override" (which is also unique in the classes) is culprit instead of "String? type". 

Here is a diff of freezed.dart files without/with the override property for someone to take a look deeper.

diff -urN risk_factor.model.freezed.dart risk_factor.model.freezed-1.dart

```
--- risk_factor.model.freezed.dart      2021-09-01 10:35:41.000000000 -0500
+++ risk_factor.model.freezed-1.dart    2021-09-01 10:35:20.000000000 -0500
@@ -21,10 +21,11 @@
 class _$RiskFactorModelTearOff {
   const _$RiskFactorModelTearOff();
 
-  _RiskFactorModel call({String? type, String? value}) {
+  _RiskFactorModel call({String? type, String? value, String? override}) {
     return _RiskFactorModel(
       type: type,
       value: value,
+      override: override,
     );
   }
 
@@ -40,6 +41,7 @@
 mixin _$RiskFactorModel {
   String? get type => throw _privateConstructorUsedError;
   String? get value => throw _privateConstructorUsedError;
+  String? get override => throw _privateConstructorUsedError;
 
   Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
   @JsonKey(ignore: true)
@@ -52,7 +54,7 @@
   factory $RiskFactorModelCopyWith(
           RiskFactorModel value, $Res Function(RiskFactorModel) then) =
       _$RiskFactorModelCopyWithImpl<$Res>;
-  $Res call({String? type, String? value});
+  $Res call({String? type, String? value, String? override});
 }
 
 /// @nodoc
@@ -68,6 +70,7 @@
   $Res call({
     Object? type = freezed,
     Object? value = freezed,
+    Object? override = freezed,
   }) {
     return _then(_value.copyWith(
       type: type == freezed
@@ -78,6 +81,10 @@
           ? _value.value
           : value // ignore: cast_nullable_to_non_nullable
               as String?,
+      override: override == freezed
+          ? _value.override
+          : override // ignore: cast_nullable_to_non_nullable
+              as String?,
     ));
   }
 }
@@ -89,7 +96,7 @@
           _RiskFactorModel value, $Res Function(_RiskFactorModel) then) =
       __$RiskFactorModelCopyWithImpl<$Res>;
   @override
-  $Res call({String? type, String? value});
+  $Res call({String? type, String? value, String? override});
 }
 
 /// @nodoc
@@ -107,6 +114,7 @@
   $Res call({
     Object? type = freezed,
     Object? value = freezed,
+    Object? override = freezed,
   }) {
     return _then(_RiskFactorModel(
       type: type == freezed
@@ -117,6 +125,10 @@
           ? _value.value
           : value // ignore: cast_nullable_to_non_nullable
               as String?,
+      override: override == freezed
+          ? _value.override
+          : override // ignore: cast_nullable_to_non_nullable
+              as String?,
     ));
   }
 }
@@ -124,7 +136,7 @@
 /// @nodoc
 @JsonSerializable()
 class _$_RiskFactorModel implements _RiskFactorModel {
-  _$_RiskFactorModel({this.type, this.value});
+  _$_RiskFactorModel({this.type, this.value, this.override});
 
   factory _$_RiskFactorModel.fromJson(Map<String, dynamic> json) =>
       _$$_RiskFactorModelFromJson(json);
@@ -133,10 +145,12 @@
   final String? type;
   @override
   final String? value;
+  @override
+  final String? override;
 
   @override
   String toString() {
-    return 'RiskFactorModel(type: $type, value: $value)';
+    return 'RiskFactorModel(type: $type, value: $value, override: $override)';
   }
 
   @override
@@ -146,14 +160,18 @@
             (identical(other.type, type) ||
                 const DeepCollectionEquality().equals(other.type, type)) &&
             (identical(other.value, value) ||
-                const DeepCollectionEquality().equals(other.value, value)));
+                const DeepCollectionEquality().equals(other.value, value)) &&
+            (identical(other.override, override) ||
+                const DeepCollectionEquality()
+                    .equals(other.override, override)));
   }
 
   @override
   int get hashCode =>
       runtimeType.hashCode ^
       const DeepCollectionEquality().hash(type) ^
-      const DeepCollectionEquality().hash(value);
+      const DeepCollectionEquality().hash(value) ^
+      const DeepCollectionEquality().hash(override);
 
   @JsonKey(ignore: true)
   @override
@@ -167,7 +185,8 @@
 }
 
 abstract class _RiskFactorModel implements RiskFactorModel {
-  factory _RiskFactorModel({String? type, String? value}) = _$_RiskFactorModel;
+  factory _RiskFactorModel({String? type, String? value, String? override}) =
+      _$_RiskFactorModel;
 
   factory _RiskFactorModel.fromJson(Map<String, dynamic> json) =
       _$_RiskFactorModel.fromJson;
@@ -177,6 +196,8 @@
   @override
   String? get value => throw _privateConstructorUsedError;
   @override
+  String? get override => throw _privateConstructorUsedError;
+  @override
   @JsonKey(ignore: true)
   _$RiskFactorModelCopyWith<_RiskFactorModel> get copyWith =>
       throw _privateConstructorUsedError;
```

**Comment by jakemac53** [comment]
It is likely just failing on the first field it sees, and is likely not directly related to any specific field. The only annotations I see are `@override` so it makes me think that is the annotation that it is having a problem constructing.

It looks like the `freezed_annotation` package should be exporting `package:meta/meta.dart` though which is where that annotation comes from, so it isn't immediately clear what the problem is.

**Comment by jakemac53** [comment]
If you could post the entire generated file content instead of a diff that might be more helpful.

**Comment by jakemac53** [comment]
Oh actually I guess `@override` is a core thing not from meta anyways, for some reason I thought it came from meta.

**Comment by chunghha** [comment]
[risk_factor.model.zip](https://github.com/dart-lang/source_gen/files/7092747/risk_factor.model.zip)
Zip file attached. freezed-1.dart is generated with the "override" property.

**Comment by jakemac53** [comment]
Oh of course!!! The problem is with the `override` property, because that is shadowing the `override` constant from `dart:core` which is trying to be used as a constant.

You can't annotate something with a reference to a field (which `override` now refers to in that scope), and so it fails to resolve the annotation. And then the error handling code for that fails with this other error as mentioned above.

The solution would be to rename the field, I don't think there is really any other good option. Normally you would have the option to import `dart:core` with a prefix and use that, but since `freezed` is generating to a part file it can't add imports and do it that way, unfortunately.

**Comment by chunghha** [comment]
These model classes are used to hold data from backend APIs so the property name is from there.

I don't know how "override" is impactful to source_gen compared to "type" and "value". (Just to me, those are all keyword.)

As workaround, using @JsonKey generates the model.g.dart. Nevertheless, I just hope this issue can be resolved. Thanks a lot, @jakemac53 for taking a look deeper.

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'risk_factor.model.freezed.dart';
part 'risk_factor.model.g.dart';

@freezed
class RiskFactorModel with _$RiskFactorModel {
  factory RiskFactorModel({
    String? type,
    String? value,
    // * workaround till https://github.com/dart-lang/source_gen/issues/555 resolved
    @JsonKey(name: 'override') String? overrideWorkaround,
  }) = _RiskFactorModel;

  factory RiskFactorModel.fromJson(Map<String, Object?> json) =>
      _$RiskFactorModelFromJson(json);
}
```

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'risk_factor.model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_RiskFactorModel _$$_RiskFactorModelFromJson(Map<String, dynamic> json) =>
    _$_RiskFactorModel(
      type: json['type'] as String?,
      value: json['value'] as String?,
      overrideWorkaround: json['override'] as String?,
    );

Map<String, dynamic> _$$_RiskFactorModelToJson(_$_RiskFactorModel instance) =>
    <String, dynamic>{
      'type': instance.type,
      'value': instance.value,
      'override': instance.overrideWorkaround,
    };

```

**Comment by jakemac53** [comment]
Note that there really is nothing that the source_gen can do in this case, unfortunately. There is a bug here, but fixing it wouldn't fix your problem (it would just fix the reporting of the problem).

I am not sure if there is a creative solution to the problem on the freezed side of things...

**Comment by chunghha** [comment]
Besides, "flutter analyze ." throws the below. Is this can be suppressed?

[   +5 ms]    **info • The annotation 'JsonKey' can only be used on fields or getters • risk_factor.model.dart:12:6 •
invalid_annotation_target**
[   +8 ms] "flutter analyze" took 1,681ms.
[   +6 ms] 1 issue found. (ran in 1.1s)
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:176:7)
           <asynchronous suspension>
           #2      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:138:7)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>

**Comment by chunghha** [comment]
freezed side reviewed but no actual solution to fix. I am fine with using the JsonKey workaround so closing this.

**Comment by jakemac53** [comment]
Ya, I did try to see if I could come up with a creative fix as well but I couldn't.

The only option I can think of, is freezed could detect this situation and ask you to add a prefixed import to `dart:core`, so something like `import 'dart:core' as core;`. And then if it saw that it could use `@core.override` instead, which would work.

But that is quite a bit of work for freezed to do, to work around a situation that has other workarounds. And honestly having a field called `override` is probably generally just best avoided 🤷‍♂️ .
