### ISSUE TITLE
`generateForAnnotatedElement` not called for annotated `library` directives

### ISSUE THREAD

**Issue by rlch** [dart-lang/source_gen#558]
Hey!

I'm trying to use `GeneratorForAnnotation` with a `library` directive, but it only seems to work if I use my annotation on a class defined in the same file.

**Example:**

```dart
import 'package:meta/meta_meta.dart';

const barrel = Barrel('./');

class Barrel {
  const Barrel(this.path, {this.ignore = const {}, this.headerDepth = 1});

  final String path;
  final Set<String> ignore;
  final int headerDepth;
}
```

Annotating an arbitrary class generated `library_example.barrel.dart` successfully as expected; 
```dart
library example;

import 'package:pearl_annotations/pearl_annotations.dart';

part 'library_example.barrel.dart';

@barrel
class LibraryExample {
  LibraryExample();
}
```

but annotating the library directive doesn't work (is not recognized by `GeneratorForAnnotation`):
```dart
@barrel
library example;
```

**Comment by natebosch** [comment]
We currently only inspect annotations on the top level elements of a library, but not the `LibraryElement` itself.

We should be able to easily search also the `LibraryElement`, we just need to make a decision about _which level_ of API it makes sent to to add that inclusion. An inclusion at an earlier API in this list implies inclusion at all later APIs. So we need to think about the users of these (early in the list) APIs and decide whether it makes sense for the users of those APIs.

We can include it in:
- `LibraryReader.allElements`
- `LibraryReader.annotatedWith`/`annotatedWithExact`
- `generateForAnnotation`

@kevmoo @jakemac53 - Do you have any opinion on whether the `LibraryReader.allElements` should include the `LibraryElement` itself?

**Comment by kevmoo** [comment]
Very meta of us. :-)

Seems reasonable, although I fear a breaking change...a bit

**Comment by jakemac53** [comment]
I think probably `LibraryReader.allElements` makes sense. @kevmoo any particular concerns around the breakage? I think the way these apis are used it's probably fine.

**Comment by kevmoo** [comment]
Just worried about behavior change – nothing explicit

**Comment by natebosch** [comment]
I'll double check the flakes, but I think this looks OK on an internal presubmit. I'm inclined to push forward with it as non-breaking.

**Comment by kevmoo** [comment]
Go for it!
