### ISSUE TITLE
Why _Builder extends Builder is private?

### ISSUE THREAD

**Issue by francescoflora** [dart-lang/source_gen#567]
Hi, why have you created _Builder as private class? How can i implement a custom builder for my own purposes?

source_gen -> src -> builder.dart

I would create a builder that generate a dart file without a "part / part of" reference into it.
To do this, actually, i need to copy the builder.dart file in my lib.

**Comment by jakemac53** [comment]
We expose the `LibraryBuilder` class which should do what you want. The `_Builder` class is private so we can more easily evolve its api and not worry about breaking changes to that class.
