### ISSUE TITLE
Question: Is it possible to generate multiple files from one annotation?

### ISSUE THREAD

**Issue by Sewx** [dart-lang/source_gen#568]
Currently I'm using multiple annotation to generate a file (1 annotation = 1 file). Is there a way to generate all the files using 1 annotation?

**Comment by jakemac53** [comment]
Can you explain more the use case? Are you outputting multiple dart files for a single annotation, or other files? Is there a fixed known number of output files or are you trying to output a variable number of files?

We do have the `additionalOutputExtensions` option on all the builder classes which you can use to output extra files, but that isn't intended to use for outputting multiple extra Dart files and using it as such might cause issues.

**Comment by Sewx** [comment]
Currently I am using 3 annotations to generate 3 dart files.

```dart
@annotationOne
@annotationTwo
@annotationThree
class foo{
  //some code
}
```

The 3 annotations will output annotation_one.g.dart, annotation_two.foo.dart and annotation_three.fooTwo.dart.

Is it possible to produce the same output but using only one annotation like this.

```dart
@annotationForAll
class foo{
  //some code
}
```

And yes there are a fixed number of files that I want to output. As mentioned above, I currently have 3 annotation to produce 3 dart files.

**Comment by jakemac53** [comment]
@Sewx are these part files or separate libraries? If they are separate libraries you could likely just use the `additionalOutputExtensions` configuration to define the extra outputs - but you would have to manually write those files using the `buildStep` which is a bit awkward for this package.

Some other options:

- Write 3 separate generators (maybe what you are already doing?) - they should all be able to generate based off of the same annotation. You could still expose these all under a single configuration for users if you wanted to (you can list multiple builder factories in the `build.yaml`).
- Just use `package:build` directly, so extend the `Builder` class. You could likely still utilize this package as a library to help find annotations, evaluate constants, etc. Then you can define your own outputs and things are generally more flexible.

**Comment by Sewx** [comment]
One annotation produces a part file while the other two are libraries.

**Comment by jakemac53** [comment]
> One annotation produces a part file while the other two are libraries.

Ya so then using a `SharedPartBuilder` or `PartBuilder` with `additionalOutputExtensions` is probably the easiest approach. But you will have to manually handle the outputting of the extra libraries.
