### ISSUE TITLE
Question: Generating dart file from an xml file?

### ISSUE THREAD

**Issue by Sewx** [dart-lang/source_gen#579]
I am just wondering if it's possible to generate a dart file from an xml file with build or source_gen. The xml file contains the contents of the dart file.

**Comment by jakemac53** [comment]
You would want to use the `build` package directly and not `source_gen` (source_gen is pretty specific to generating dart code from other dart code). But the lower level `Builder` class from `package:build` is very flexible and can generate any kind of file from any other kind of file.
