### ISSUE TITLE
How to generate a single output file for multiple input files?

### ISSUE THREAD

**Issue by BenVercammen** [dart-lang/source_gen#586]
Something I haven't been able to figure out, is how to create or configure a `Buider` and/or `Generator` class in such a way that only a single "**something.g.dart**" is being generated as output for multiple input files.

What I'm trying to do:
 - **input:** annotated classes spread across multiple `.dart` files in the `src/lib` dir
 - **output:** a single `.g.dart` file containing classes/methods/... based on the collected annotated input classes

I actually managed to hack together a custom `Builder` implementation from scratch. The only issue is that I can't seem to access the input files as a `library` elements, so I have to do the file parsing in a very basic String-based way. When trying to build upon existing builders and other classes, I often ran into __protected classes/methods_ I couldn't leverage for my own purpose. 

To me, this does seem to be not that uncommon a requirement for code generation, so I'm wondering if I'm missing something obvious? Is there an available work-around for my specific use case? Or would it need a new type of Builder to achieve this?

Any pointers are greatly appreciated. I am willing to work on a pull request if required and when steered in the right direction.

**Comment by jakemac53** [comment]
A custom builder implementation is likely a good approach, see https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md which discusses in detail how you can do this. Specifically the section on [synthetic inputs](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md#writing-the-builder-using-a-synthetic-input) may be of use to you.



> The only issue is that I can't seem to access the input files as a `library` elements, so I have to do the file parsing in a very basic String-based way.

There used to be a limitation that you could not resolve libraries that weren't transitively imported by the **primary input** (the input you are basing your output extension on). This restriction was removed in `build_resolvers` version `1.3.0`, so you should be able to do it now. Can you verify your version (you can run `dart pub deps` to see the versions of transitive deps).

**Comment by BenVercammen** [comment]
Thank you, this was exactly what I was looking for!
