### ISSUE TITLE
Provide way to exclude some generators from command line.

### ISSUE THREAD

**Issue by dikmax** [dart-lang/source_gen#59]
Here's my use case. I have 2 generators. 

First is slow, downloads some files and then generates code which usually doesn't change.
Second is fast, I use it to generate unit-tests. It could be called several times in a minute. 
Right now I have to comment code that calls first generator. But it will be very convenient to just pass some args to prevent first generator from being run.

**Comment by matanlurey** [comment]
I don't think `source_gen` will ever support this.

Of course since you write the `tool/build.dart` yourself, you can do what you want.
