### ISSUE TITLE
How to debug generators code and write tests for it?

### ISSUE THREAD

**Issue by Timu5** [dart-lang/source_gen#592]
So I'm struggling  with possibility of debugging and writing tests for generator, because it's invoked by build is seems like its not trivial to do. 

Any tips on how to do that?

**Comment by jakemac53** [comment]
Another option is to create a fake package using test_descriptor, actually run build_runner on the package, and compare against the outputs. But that will be many times slower to run.

**Comment by Timu5** [comment]
Thanks!
