### ISSUE TITLE
import dart mirror that haven't support null-safety

### ISSUE THREAD

**Issue by Hoang-Nguyenn** [dart-lang/source_gen#593]
Hi bro, now i'm using this one but got small problem that dart:mirror that doesn't support nullsafety

package:source_gen/src/type_checker.dart that imports:
dart:mirrors where dart:mirrors is inaccessible.

Are we have anyway to update it ?

**Comment by natebosch** [comment]
> dart:mirror that doesn't support nullsafety

All SDK libraries support null safety.

> package:source_gen/src/type_checker.dart that imports:
> dart:mirrors where dart:mirrors is inaccessible.

Mirrors is accessible on the VM, which is the only supported platform for running code generation. If you are trying to import `source_gen` from a flutter app it will not work.
