### ISSUE TITLE
Why should non-SharedPartBuilders never use a `.g.dart` extension?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/source_gen#598]
The source_gen `README.md` says:

> When using `SharedPartBuilder` it should always be configured to `build_to: cache` (hidden files) and apply the `combining_builder` from this package. The combining builder reads in all the pieces written by different shared part builders and writes them to the final `.g.dart` output in the user's source directory. You should never use the `.g.dart` extension for any other Builder.

But why?  What would happen if `.g.dart` is used for other Builders?  Should that rule also apply to files generated without using `source_gen`?

I had previously assumed that the "g" in `.g.dart` just meant "generated" and that it it was a convention that applied to all generated files.  Being able to easily classify *all* generated files seems like it'd be generally useful (e.g. to exclude from source control, the analyzer).

**Comment by natebosch** [comment]
For a while we did use the `.g.dart` convention more widely, but eventually we found that it works better if most builders use unique extensions to avoid conflicts. The `.g.dart` convention remains solely for the builders that collaborate - the uber generator internally and source gen `SharedPartBuilders` externally.

> What would happen if `.g.dart` is used for other Builders?

If it gets used in any project using `SharedPartBuilder` then it would likely cause conflicts.

> Should that rule also apply to files generated without using `source_gen`?

Yes, most builders that aren't using `source_gen` should also avoid `.g.dart` and instead pick something more specific.

**Comment by jamesderlin** [comment]
Thanks!

> eventually we found that it works better if most builders use unique extensions to avoid conflicts.

IMO it would have been nice if `.g.dart` for were kept for all generated files and if `SharedPartBuilder` instead used its own extension (e.g. `.part.g.dart`), and then other packages could use `.package_name.g.dart`.  But probably way too late now...

> If it gets used in any project using `SharedPartBuilder` then it would likely cause conflicts.

Maybe add that to the `README.md`?
