### ISSUE TITLE
Is there a way to find declared source of predefined annotations? 

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/source_gen#615]
```dart
const predefinedAnnotation = SomeAnnotation('this is predefined');

@predefinedAnnotation  // this is the first case
@SomeAnnotation('this is defined as it's needed') // this is the second case
class SomeClass {
}
```

In this case, I am currently getting a declaration by using below code. 

```dart
// `element `is `ClassElement` of SomeClass
for (final annotations in element. metadata) {
  print(annotations.toSource());
}
```

In the first case (predefined annotation), it only prints `predefinedAnnotation`, the name of the constant variable. 
In the second case, it prints what I want. The full code of `@SomeAnnotation('this is defined as it's needed')`. 

Is there a way to get the full code in case of `predefinedAnnotation`?

**Comment by natebosch** [comment]
The first step is to get a `DartObject` for the annotation. I think `annotations.computConstantValue()` works in most cases, but if the annotation is not resolvable it may return null. With the `DartObject` you can use a `ConstantReader` to read fields from it.
https://pub.dev/documentation/source_gen/latest/source_gen/ConstantReader-class.html

See also `LibraryReader` which has methods for finding annotated elements and creating a `ConstantReader` for the annotations.

https://pub.dev/documentation/source_gen/latest/source_gen/LibraryReader-class.html
