### ISSUE TITLE
Is it possible to create a number of files from a text file containing a list of values?

### ISSUE THREAD

**Issue by atreeon** [dart-lang/source_gen#618]
So I have a text file containing a list of values.  What is the best way to read this list of values and then create a list of files from them?  Is `source_gen` the right tool for the job?

ie a,b,c,d => a.dart, b.dart, c.dart, d.dart

**Comment by jakemac53** [comment]
While a reasonable thing to want to do, this is not supported by the `build` package generally. We require that all known outputs exist before any actions have ran or files have been read. That has the follow on effect that you can't have dynamic outputs.

There is one exception to this rule, which is the `PostProcessBuilder`. But it really shouldn't be used to output Dart files. Any files created by a PostProcessBuilder cannot be used as inputs to any other actions.
