### ISSUE TITLE
How to recognize if the import using "as"

### ISSUE THREAD

**Issue by tatashidayat** [dart-lang/source_gen#637]
Hi guys,
I am using source_gen 1.2.2, and I have this case:
```dart
import 'package:my_package_a/a.dart';
import 'package:my_package_b/a.dart' as old;

@MyAnnotation()
class MyUsecase {
  Future<old.A> getOldA() {
      // ...logic here
  }
  Future<A> getA() {
     // ...logic here
  }
}
```

I noticed `getOldA` the value of `returnType.typeArguments` is `A` which i expect it should be `old.A`.

How can I know if it's `A` or `old.A`?

#### Notes:
The `A` class is dynamic so I can't use `TypeChecker` to verify the type.

Thank you

**Comment by jakemac53** [comment]
This is more of an analyzer question, but I believe you need to go to the `ast` for the element (you can use [astNodeFor](https://pub.dev/documentation/build/latest/build/Resolver/astNodeFor.html) to get that).

That should allow you to get the `Identifier` for the type argument, which you can check if it is a `PrefixedIdentifier` and that will give you access to the prefix.

**Comment by jakemac53** [comment]
Going to close this for now but you can respond if you have more questions
