### ISSUE TITLE
Can't check if an enum implements a class

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/source_gen#638]
Dart SDK version: 2.19.0 (stable)
analyzer 5.4.0

```dart
class Bar {
  bool get bar => false;
}

enum Foo with Bar {
  foo(true);

  Foo(this.bar);

  @override
  final bool bar;
}
```

the builder: 

```dart
void checkType(DartType type) {
  final fooCheck = TypeChecker.fromRuntime(Foo);

  print(fooCheck.isAssignableFromType(type); // false but should be true
  print(type); // Foo
  print(type.element);  // enum Foo with Bar
}
```

**Comment by jakemac53** [comment]
Transferred for now, if we determine there is an analyzer issue we can transfer it back

**Comment by jodinathan** [comment]
> Oh, maybe this is more specific to `TypeChecker` from the `source_gen` package?

A wild guess it uses the analyzer behind the scenes, nevertheless we are using `source_gen` 1.2.6

**Comment by jakemac53** [comment]
It does use analyzer but has some custom logic as well, and I think it might have special handling for enums

**Comment by kevmoo** [comment]
@scheglov – ideas here?

**Comment by scheglov** [comment]
I don't understand the original message, in the combination with the issue title.
What is `type` in `checkType()`?
If it is `Foo`, then why do you check that `fooCheck.isAssignableFromType`.
Either some names are wrong, or I don't understand something.

If I try to guess what you trying to do, then this code shows how to do it in the analyzer:
```dart
  solo_test_XXX() async {
    await assertNoErrorsInCode(r'''
class Bar {
  bool get bar => false;
}

enum Foo with Bar {
  foo(true);

  const Foo(this.bar);

  @override
  final bool bar;
}
''');

    final foo = findElement.enum_('Foo');
    final bar = findElement.class_('Bar');
    print(foo.allSupertypes.map((t) => t.element).contains(bar));
  }
```

**Comment by jakemac53** [comment]
Fwiw I wrote a test for this and is passes, https://github.com/dart-lang/source_gen/pull/639

**Comment by jakemac53** [comment]
Yeah the example code is just wrong `isAssignableFromType` checks that the given argument is assignable to the reciever. Presumably you have a `Bar` type which you are passing to this function - but a `Bar` is not assignable to a `Foo`, only the other way around.

**Comment by jodinathan** [comment]
yeah @jakemac53 is correct regarding the example sorry about that.  

your test mixin:

```dart
mixin MyEnumMixin on Enum {
   int get value => 1;
 }

 enum MyEnumWithMixin with MyEnumMixin { foo, bar }
```

my class is a little bit different from your `mixin`:  `abstract class StaticModel implements BaseModel, Enum {}`

we will make some changes to make it look like yours and check if that's the problem

**Comment by jakemac53** [comment]
Feel free to make a test case similar to my PR above and send a PR for it also - that is the easiest thing to go about diagnosing/fixing :).

**Comment by jodinathan** [comment]
found the problem.  
`source_gen` version `1.2.6` has this code:  

```dart
bool isAssignableFrom(Element element) =>
      isExactly(element) ||
      (element is ClassElement && element.allSupertypes.any(isExactlyType));
```

While the same method in the [master channel](https://github.com/dart-lang/source_gen/blob/master/source_gen/lib/src/type_checker.dart#L167) is checking for `InterfaceElement` instead.

I guess that is the reason your test passed while the error occurs in our builder

**Comment by kevmoo** [comment]
Oh! We just need to publish! We can do that!

**Comment by jakemac53** [comment]
Oh! that makes sense haha
