### ISSUE TITLE
GeneratorForAnnotation uses Set instead of List for return value

### ISSUE THREAD

**Issue by Dampfwalze** [dart-lang/source_gen#648]
In `GeneratorForAnnotation.generate`:

https://github.com/dart-lang/source_gen/blob/f1011be303c6937c55fde297680bf772d414ea9d/source_gen/lib/src/generator_for_annotation.dart#L48-L65

On line `50`:
`values` should be a List instead of a Set.

This is an example of a generator that would not work, because it returns `}` twice (Note, that the whitespaces will be trimmed away by `normalizeGeneratorOutput`):
```dart
class SubclassGenerator extends GeneratorForAnnotation<Annotation> {
  @override
  generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) sync* {
    yield "class ${element.name}Subclass extends ${element.name} {";
    yield "  ${element.name}Subclass() {";
    yield "    print('Hello world: ${element.name}!');";
    yield "  }";
    yield "}";
  }
}
```

Furthermore, a set does not have the requirement of preserving any order.

**Comment by jakemac53** [comment]
I believe that this is intentional to allow generators to deduplicate helper code. But this assumes that generators are only emitting fully formed declarations (I am not sure if this is documented anywhere though).

**Comment by d-markey** [comment]
I can confirm that's intended. You can find an example at https://github.com/d-markey/squadron_builder/blob/main/lib/src/worker_assets.dart#LL137C31-L137C31 where the code for each individual class is yielded in a `sync*` method.

**Comment by natebosch** [comment]
I think we could document this better.

**Comment by kevmoo** [comment]
A VERY intentional feature. Glad @natebosch is running on documenting it!
