### ISSUE TITLE
Allow customization of the resulting JSON keys

### ISSUE THREAD

**Issue by johnryan-wf** [dart-lang/source_gen#65]
In Go, the serialized JSON for a struct can be customized using this syntax:

```go
type Foo struct {
	BarBaz string `json:"bar"`
	...
}
```

It would be great if there was a similiar annotation for properties, so that classes could use a more meaningful names for their Dart API:

```dart
@JsonSerializable()
class Foo extends Object with _$FooSerializerMixin {
  @Json("bar")
  final String barBaz;
  ...
}
```

resulting in 

```json
{
    "bar": "_"
}
```

**Comment by kevmoo** [comment]
@johnryan-wf Love the idea – pull requests welcome!
