### ISSUE TITLE
How to run this command in debug mode?

### ISSUE THREAD

**Issue by kw214** [dart-lang/source_gen#658]
How to run this command in debug mode? 

`flutter pub run build_runner build`

**Comment by jakemac53** [comment]
Do you want to debug the build itself? Or make a debug build?

Fwiw, builds are all debug builds by default, you have to pass `--release` for a release build (although few builders actually do anything different).

To debug the build script itself, see [here](https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md#how-can-i-debug-my-builder).
