### ISSUE TITLE
Broken with pkg/analyzer >= 0.26.1+15

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#67]
With 0.26.1+14: all tests pass
With 0.26.1+15: +55 -21: Some tests failed.
With 0.26.2+1 (latest): +55 -21: Some tests failed.

**Comment by bwilkerson** [comment]
Let me know if it looks like these are bugs in analyzer.

**Comment by kevmoo** [comment]
@bwilkerson well, between +14 and +15, *something* changed that breaks how source_gen does its thing.

Of course, source_gen is using undocumented APIs – but it is also being used by folks inside and outside Google.
