### ISSUE TITLE
Has any way to ignore WARNING?

### ISSUE THREAD

**Issue by normidar** [dart-lang/source_gen#698]
I have a generator output as cache use `GeneratorForAnnotation`.

But console always show a log that: 

```
class.cache must be included as a part directive in the input library with:
    part 'class.cache';
```

I want to ignore this log.

**Comment by jakemac53** [comment]
It sound like you want to produce a separate library, instead of a part file. To do this, instead of wrapping your generator in a `SharedPartBuilder`, wrap it in a `LibraryBuilder`.

**Comment by normidar** [comment]
I know it, if I do not return string, it will not print warning
