### ISSUE TITLE
Add an annotation to specify the desired location for the generated files

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/source_gen#76]
I don't want .g.dart files directly in the lib/ folder of a package. If I want to keep the source code in that folder, currently I have to move the generated files manually every time after generation.

F.e.

```
@Generate(location: "gen/")
class _SomeClass {}
```

If the location is a folder, use the same filename as currently, file.g.dart. If the location is a full path with file name, just use that part as the generated file.

Requiring an annotation for each class that needs generation would solve #74, but I'm not sure if requiring the annotation is preferable.

**Comment by a14n** [comment]
Another way to customize the generated file could be to provide an additionnal parameter to the `build` function. Something like :

```dart
main(List<String> args) async {
  print(await build(args, [new MyAwesomeGenerator()],
      librarySearchPaths: ['example/', 'lib/', 'web/', 'test/'],
      fileNamer: (String pathOfTheLibFile) => customizedOutputPath));
}
```

**Comment by stevenroose** [comment]
That would do fine too. However, it is in the library file that the `part`
statement has to reference to the file so the location is already included
in the library file.

In my opinion, the annotations should be able to do everything so that the
build function no longer is required.
If annotations are used to indicate what files to process and where to put
the generated files, the build process could just be a global pub
executable so that it is not necessary to maintain a separate file with the
build function.

**Comment by jakemac53** [comment]
@stevenroose if you don't output the files in lib, how would you import them? Using relative paths that reach into other top level folders is considered bad practice (I don't think it works if you publish your app, but that would need to be tested).

**Comment by stevenroose** [comment]
@a14n I put them in `lib/src/`. And I am considering `lib/gen/` because
they are no source files. For most libs, only top-level files in `lib/` are
intended for importing and everything in `lib/src/` is exported or
`part`-ed by top-level files.

**Comment by jakemac53** [comment]
There is another issue this, which is related to my comment on issue #74. Source gen should be easy to integrate into any build system, and many of those require the ability to declare outputs up front before reading the input files. Today that can be done without actually reading the inputs since the output file path is always the same, but this would require reading the files in order to know what the outputs might be.

**Comment by natebosch** [comment]
package:build has become more restrictive - It's no longer a source_gen limitation but a build limitation that files can only be output directly next to inputs. We've moved in this direction for the sake of consistency across build systems, and predictable behavior.
