### ISSUE TITLE
Questions about Bazel + source_gen

### ISSUE THREAD

**Issue by a14n** [dart-lang/source_gen#99]
- Will bazel and source_gen play well together when bazel will rise?
- How will source_gen work with bazel ?
- Will the build package still be used ?

**Comment by jakemac53** [comment]
> Will bazel and source_gen play well together when bazel will rise?

One of the main motivations of `package:build` (which source_gen is built on) is to be a bridge between transformers, bazel, or any other build system (such as the one that comes with package:build). We are in the process of open sourcing everything to make it work in bazel, but there is still a fair bit of work there.

> How will source_gen work with bazel ?

At a high level you will end up with a codegen build target (per package?) whose outputs you add to the srcs of the corresponding dart_library rule. How exactly this is hidden from users of the `bazelify` helpers is tbd, but there are a few options (explicit configuration via some yaml file, inferring codegen rules from your transformers section, etc).

> Will the build package still be used ?

The interfaces from the build package will still be used in bazel, but not the actual runner scripts (build, watch, serve) as bazel already does those things.

**Comment by a14n** [comment]
Thanks for the quick answers!
